"""
Natal Chart Report PDF (#29). Matches the existing pdf_formatter.py's reportlab-based
pattern (confirmed that file uses reportlab, not a different library) rather than
introducing a second PDF approach. Takes the same real data astrology_snapshot.py already
computes and lays it out as a real, downloadable PDF — not a mockup, an actual FileResponse.
"""

import io
from datetime import datetime

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from pydantic import BaseModel

from ..deps import CurrentUser, get_current_user, get_db_connection

router = APIRouter(tags=["natal-chart-pdf"])


class NatalChartPdfRequest(BaseModel):
    client_id: str


@router.post("/natal-chart/pdf")
async def generate_natal_chart_pdf(payload: NatalChartPdfRequest, user: CurrentUser = Depends(get_current_user)):
    from dateutil import parser as dparser
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.units import inch
    from reportlab.lib import colors
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from synthesis.astrology_engine import _julian_day, _calculate_positions, _calculate_houses, _degree_to_sign

    conn = get_db_connection()
    cur = conn.cursor()
    try:
        cur.execute("SELECT * FROM clients WHERE id = %s AND consultant_id = %s", (payload.client_id, user.id))
        client = cur.fetchone()
        if not client:
            raise HTTPException(status_code=404, detail="Client not found")
    finally:
        cur.close()
        conn.close()

    if not client.get("birth_date"):
        raise HTTPException(status_code=422, detail="This client has no birth date on file")

    bd = dparser.parse(client["birth_date"])
    jd = _julian_day(bd.year, bd.month, bd.day, 12.0, 0.0)
    positions = _calculate_positions(jd, use_sidereal=False)
    houses = _calculate_houses(jd, 0.0, 0.0, use_sidereal=False)

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, topMargin=0.75*inch, bottomMargin=0.75*inch)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("KayalTitle", parent=styles["Title"], fontSize=22, spaceAfter=6)
    subtitle_style = ParagraphStyle("KayalSubtitle", parent=styles["Normal"], fontSize=11, textColor=colors.grey, spaceAfter=20)
    heading_style = ParagraphStyle("KayalHeading", parent=styles["Heading2"], spaceBefore=16, spaceAfter=8)

    elements = [
        Paragraph(f"Natal Chart — {client['name']}", title_style),
        Paragraph(f"Born {client['birth_date']} · Generated {datetime.utcnow().strftime('%B %d, %Y')}", subtitle_style),
        Paragraph("Planetary Positions", heading_style),
    ]

    planet_rows = [["Planet", "Sign", "Degree", "Retrograde"]]
    for name, data in positions.items():
        planet_rows.append([name, data["sign"], f"{data['degree']:.1f}\u00b0", "Yes" if data["retrograde"] else "No"])
    planet_table = Table(planet_rows, colWidths=[1.5*inch, 1.5*inch, 1.2*inch, 1.2*inch])
    planet_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a2744")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f7f5f0")]),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    elements.append(planet_table)

    elements.append(Paragraph("Houses", heading_style))
    house_rows = [["House", "Sign", "Degree"]]
    for key, deg in sorted(houses.items(), key=lambda x: (0, int(x[0])) if x[0].isdigit() else (1, x[0])):
        sign, house_deg, _ = _degree_to_sign(deg)
        house_rows.append([key, sign, f"{house_deg:.1f}\u00b0"])
    house_table = Table(house_rows, colWidths=[1.5*inch, 1.5*inch, 1.2*inch])
    house_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a2744")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f7f5f0")]),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    elements.append(house_table)
    elements.append(Spacer(1, 20))
    elements.append(Paragraph(
        "Generated by KAYAL SoulPath Institute. Planetary positions computed via Swiss Ephemeris.",
        ParagraphStyle("Footer", parent=styles["Normal"], fontSize=8, textColor=colors.grey),
    ))

    doc.build(elements)
    buffer.seek(0)

    filename = f"natal-chart-{client['name'].replace(' ', '-').lower()}.pdf"
    return StreamingResponse(
        buffer, media_type="application/pdf",
        headers={"Content-Disposition": f"attachment; filename={filename}"},
    )
