"""
Standalone Physiognomy (face) reading — genuinely new endpoint, but built entirely on
FaceEngine/FaceReader, the same real, already-verified functions the combined reading
uses. Confirmed by reading face_reader.py in full: FaceReading already contains rich,
deterministic, rule-based interpretation for every facial feature (shape, symmetry,
proportions, forehead, eyes, brows, nose, cheeks, lips, jaw, skin, expression, aging,
parent inheritance, health zones, spiritual markers, longevity) — real interpretive text
generated by pure Python logic, not requiring an LLM pass. That's what this endpoint
returns directly, not a narrower slice of the combined synthesis.

Stateless, like name_vibration — face/palm feature extraction + rule-based interpretation
is fast enough not to need the jobs/BackgroundTasks pattern reading generation needs.
"""

from fastapi import APIRouter, Depends, File, Form, HTTPException, UploadFile

from ..deps import CurrentUser, get_current_user, get_db_connection

router = APIRouter(tags=["physiognomy"])


@router.post("/physiognomy", response_model=dict)
async def generate_physiognomy_reading(
    client_id: str = Form(...),
    face_image: UploadFile = File(...),
    user: CurrentUser = Depends(get_current_user),
):
    from synthesis.face_engine import FaceEngine
    from synthesis.face_reader import FaceReader

    conn = get_db_connection()
    cur = conn.cursor()
    try:
        cur.execute("SELECT * FROM clients WHERE id = %s AND consultant_id = %s", (client_id, user.id))
        client = cur.fetchone()
        if not client:
            raise HTTPException(status_code=404, detail="Client not found")
    finally:
        cur.close()
        conn.close()

    face_bytes = await face_image.read()

    try:
        features = FaceEngine().extract(face_bytes)
    except Exception as e:
        raise HTTPException(status_code=502, detail=f"Face analysis failed: {e}")

    if features.error:
        raise HTTPException(status_code=422, detail=f"Could not read this photo: {features.error}")

    reading = FaceReader().read(features)

    return {
        "client_id": client_id,
        "client_name": client["name"],
        "reading": reading.to_dict(),
    }
