"""
Relationship Report PDF (#44). Same reportlab pattern as natal_chart_pdf.py — tested
end-to-end there (confirmed valid %PDF- header, confirmed opens as a real document), reused
here rather than a third PDF approach.
"""

import io
from datetime import datetime

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from pydantic import BaseModel

from ..deps import CurrentUser, get_current_user, get_db_connection

router = APIRouter(tags=["relationship-report-pdf"])


class RelationshipReportPdfRequest(BaseModel):
    client_a_id: str
    client_b_id: str


@router.post("/relationship-report/pdf")
async def generate_relationship_report_pdf(payload: RelationshipReportPdfRequest, user: CurrentUser = Depends(get_current_user)):
    from dateutil import parser as dparser
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.units import inch
    from reportlab.lib import colors
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from synthesis.astrology_engine import _julian_day, _calculate_positions, _calculate_houses, compute_composite_chart

    conn = get_db_connection()
    cur = conn.cursor()
    try:
        cur.execute("SELECT * FROM clients WHERE id = %s AND consultant_id = %s", (payload.client_a_id, user.id))
        client_a = cur.fetchone()
        cur.execute("SELECT * FROM clients WHERE id = %s AND consultant_id = %s", (payload.client_b_id, user.id))
        client_b = cur.fetchone()
    finally:
        cur.close()
        conn.close()

    if not client_a or not client_b:
        raise HTTPException(status_code=404, detail="One or both clients not found")

    bd_a = dparser.parse(client_a["birth_date"])
    bd_b = dparser.parse(client_b["birth_date"])
    hour = 12.0
    jd_a = _julian_day(bd_a.year, bd_a.month, bd_a.day, hour, 0.0)
    jd_b = _julian_day(bd_b.year, bd_b.month, bd_b.day, hour, 0.0)
    positions_a = _calculate_positions(jd_a, use_sidereal=False)
    positions_b = _calculate_positions(jd_b, use_sidereal=False)
    houses_a = _calculate_houses(jd_a, 0.0, 0.0, use_sidereal=False)
    houses_b = _calculate_houses(jd_b, 0.0, 0.0, use_sidereal=False)

    try:
        composite = compute_composite_chart(positions_a, positions_b, houses_a, houses_b, system="western")
    except Exception as e:
        raise HTTPException(status_code=502, detail=f"Composite chart calculation failed: {e}")

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, topMargin=0.75*inch, bottomMargin=0.75*inch)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("KayalTitle", parent=styles["Title"], fontSize=22, spaceAfter=6)
    subtitle_style = ParagraphStyle("KayalSubtitle", parent=styles["Normal"], fontSize=11, textColor=colors.grey, spaceAfter=20)
    heading_style = ParagraphStyle("KayalHeading", parent=styles["Heading2"], spaceBefore=16, spaceAfter=8)
    body_style = ParagraphStyle("KayalBody", parent=styles["Normal"], fontSize=10, spaceAfter=6)

    elements = [
        Paragraph(f"Union Blueprint — {client_a['name']} &amp; {client_b['name']}", title_style),
        Paragraph(f"Generated {datetime.utcnow().strftime('%B %d, %Y')}", subtitle_style),
        Paragraph(f"Composite Ascendant: {composite['composite_asc']['sign']}", heading_style),
        Paragraph(composite["composite_asc"]["reading"], body_style),
        Paragraph("Composite Positions", heading_style),
    ]

    rows = [["Planet", "Sign", "Degree"]]
    for planet, data in composite["composite_positions"].items():
        rows.append([planet, data["sign"], f"{data['degree']:.1f}\u00b0"])
    table = Table(rows, colWidths=[1.5*inch, 1.5*inch, 1.2*inch])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a2744")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f7f5f0")]),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    elements.append(table)

    if composite.get("composite_signals"):
        elements.append(Paragraph("Signals", heading_style))
        for s in composite["composite_signals"]:
            elements.append(Paragraph(f"<b>{s['domain'].replace('_', ' ').title()}:</b> {s['reading']}", body_style))

    elements.append(Spacer(1, 20))
    elements.append(Paragraph(
        "Generated by KAYAL SoulPath Institute. Composite chart computed via Swiss Ephemeris.",
        ParagraphStyle("Footer", parent=styles["Normal"], fontSize=8, textColor=colors.grey),
    ))

    doc.build(elements)
    buffer.seek(0)

    filename = f"union-blueprint-{client_a['name'].replace(' ', '-').lower()}-{client_b['name'].replace(' ', '-').lower()}.pdf"
    return StreamingResponse(
        buffer, media_type="application/pdf",
        headers={"Content-Disposition": f"attachment; filename={filename}"},
    )
