// ============================================================
// LIFE PATH & DESTINY — 12 Tools
// Domain: life-path
// Route: /domain/life-path-destiny
// Source of truth: tool_registry.py
// ============================================================

export interface LifePathTool {
  id: string
  name: string
  tagline: string
  emoji: string
  hook: string
  price: number
  domain: 'life-path'
  isPopular?: boolean
  isBestSeller?: boolean
  isNew?: boolean
  isFlagship?: boolean
  rating?: number
  reviewCount?: number
  requiresImage?: { type: 'face' | 'palm' | 'both' } | null
  requiresPartner?: boolean
  whatYouGet: string[]
  guidanceType?: 'spiritual-remedy' | 'practical-solution' | 'daily-guidance'
  guidanceText?: string
  upsell?: { id: string; name: string; price: number }
  deliveryMinutes?: number
}

export const lifePathTools: LifePathTool[] = [
  {
    id: 'life-path-deep-dive',
    name: 'The Life Path Deep Dive',
    tagline: 'Your Life Path number decoded in full — not the generic version',
    emoji: '🌟',
    price: 57,
    domain: 'life-path',
    isPopular: true,
    isBestSeller: true,
    isFlagship: true,
    rating: 4.9,
    reviewCount: 2341,
    deliveryMinutes: 20,
    hook: 'Most Life Path readings describe the archetype and stop there. The archetype is the starting point, not the destination. Your Life Path expresses differently depending on your Pinnacle phase, Personal Year, karmic debt configuration, and the specific challenges you agreed to master. This reading covers the full picture.',
    whatYouGet: [
      'Your Life Path number and its complete expression across all life domains',
      'How your Life Path interacts with your current Pinnacle phase to shape what this chapter requires',
      'Your natural strengths from your Life Path and the shadow side that accompanies them',
      'The specific lesson your Life Path is asking you to demonstrate right now',
      'How your Life Path shapes your relationship style, wealth approach, and spiritual path',
      'The one decision available in the next 12 months that most fully expresses your Life Path',
    ],
    guidanceType: 'practical-solution',
    guidanceText: 'A Life Path alignment guide with the specific next move most supported by your number, timed to your current Pinnacle and Personal Year.',
    upsell: { id: 'complete-purpose-synthesis', name: 'The Complete Purpose Synthesis', price: 97 },
  },
  {
    id: 'soul-contract-reading',
    name: 'The Soul Contract Reading',
    tagline: 'What you agreed to before you arrived — decoded completely',
    emoji: '📋',
    price: 47,
    domain: 'life-path',
    isPopular: true,
    isFlagship: true,
    rating: 4.9,
    reviewCount: 1543,
    deliveryMinutes: 20,
    hook: 'Your Life Path, Karmic Debts, Destiny number, and Nodal axis together encode a set of soul commitments with remarkable specificity. This reading decodes the contract in full, including the clauses you have been avoiding and the agreements that are currently asking for your attention.',
    whatYouGet: [
      'Three primary soul agreements encoded in your chart and what each is asking of you',
      'Which agreements are currently being honoured and where life flows as a result',
      'Which agreements are being avoided and where life resists as a result',
      'Karmic debts still outstanding and what resolving them looks like practically',
      'Your soul\'s ultimate contribution, what this life is building toward in the long arc',
      'Timing, which agreements become most active in your current chapter',
    ],
    guidanceType: 'practical-solution',
    guidanceText: 'A soul contract alignment guide with specific practical action for each primary soul agreement, calibrated to your current Pinnacle and Personal Year.',
    upsell: { id: 'complete-purpose-synthesis', name: 'The Complete Purpose Synthesis', price: 97 },
  },
  {
    id: 'pinnacle-reading',
    name: 'The Pinnacle Reading',
    tagline: 'The life chapter you are actually in — and what it requires',
    emoji: '⛰️',
    price: 47,
    domain: 'life-path',
    isPopular: true,
    rating: 4.8,
    reviewCount: 2103,
    deliveryMinutes: 20,
    hook: 'Everything happening in your life right now is not random. You are in a specific chapter. Most people live through their Pinnacles unconsciously, fighting the chapter instead of harvesting what it offers. This reading gives you the complete map of your current Pinnacle and what it is specifically asking of you.',
    whatYouGet: [
      'Your current Pinnacle number, precise age range, and what this chapter is specifically for',
      'The gift of this Pinnacle, what it opens up that was not available in the previous chapter',
      'The challenge of this Pinnacle, what it is asking you to release or master',
      'How long remains in this chapter and what the next Pinnacle brings',
      'The retrospective, what the previous Pinnacle was building toward',
      'The one move that harvests the maximum from your current chapter',
    ],
    guidanceType: 'practical-solution',
    guidanceText: 'A Pinnacle harvest guide with specific moves for extracting maximum value from your current chapter, timed to where you are within it.',
    upsell: { id: 'nine-year-cycle-reading', name: 'The Nine-Year Cycle Reading', price: 47 },
  },
  {
    id: 'nine-year-cycle-reading',
    name: 'The Nine-Year Cycle Reading',
    tagline: 'The map of your entire life — past, present, and future',
    emoji: '∞',
    price: 47,
    domain: 'life-path',
    isPopular: true,
    isBestSeller: true,
    rating: 4.8,
    reviewCount: 4123,
    deliveryMinutes: 20,
    hook: 'Every nine years your entire life resets. Most people live these cycles unconsciously, pushing in rest years and resting in push years. This reading gives you the complete map. The retrospective alone, seeing how the past 18 years mapped precisely to the cycles, is the accuracy demonstration that changes how people see their entire life.',
    whatYouGet: [
      'Retrospective map of your last two 9-year cycles and what each year was for',
      'Your exact cycle currently active and what it specifically demands',
      'Forward map of the next nine years with what each year calls for',
      'The specific mistake most people make in your current Personal Year',
      'One decision to make now versus one to wait on',
      'How your Pinnacle cycle overlays with your Personal Year right now',
    ],
    guidanceType: 'practical-solution',
    guidanceText: 'A cycle-aligned action guide with the specific type of move most supported in your current Personal Year and one decision to make now versus one to defer.',
    upsell: { id: 'annual-destiny-forecast', name: 'The Annual Destiny Forecast', price: 77 },
  },
  {
    id: 'karmic-lessons-reading',
    name: 'The Karmic Lessons Reading',
    tagline: 'The lessons encoded in your chart that keep showing up until learned',
    emoji: '🧹',
    price: 37,
    domain: 'life-path',
    rating: 4.8,
    reviewCount: 987,
    deliveryMinutes: 20,
    hook: 'Karmic lessons are not punishments. They are the specific capacities your soul agreed to develop in this lifetime that were absent or underdeveloped in previous ones. They show up as recurring themes, inexplicable weaknesses, and situations that seem to find you regardless of what you do differently.',
    whatYouGet: [
      'Your karmic lessons identified from the missing numbers in your blueprint',
      'The specific way each lesson shows up as a recurring pattern in your life',
      'Why these particular lessons were chosen for this incarnation',
      'The difference between a karmic lesson being worked versus being avoided',
      'The specific practice that most accelerates the completion of each lesson',
      'What becomes available once each karmic lesson has been demonstrated',
    ],
    guidanceType: 'spiritual-remedy',
    guidanceText: 'A karmic lesson completion guide with specific practices for demonstrating each lesson, calibrated to your current cycle.',
    upsell: { id: 'soul-contract-reading', name: 'The Soul Contract Reading', price: 47 },
  },
  {
    id: 'north-node-reading',
    name: 'The North Node Reading',
    tagline: 'The direction your soul is being pulled toward in this lifetime',
    emoji: '🧲',
    price: 37,
    domain: 'life-path',
    isPopular: true,
    rating: 4.8,
    reviewCount: 1432,
    deliveryMinutes: 20,
    hook: 'Your North Node is the point in your chart where the soul is being called toward unfamiliar but necessary growth. It is always uncomfortable at first because you are moving away from what came easily in past lives. Understanding your North Node changes your relationship with the discomfort of growth.',
    whatYouGet: [
      'Your North Node sign, house, and the specific direction of soul growth it describes',
      'Your South Node, the comfort zone that feels safe but keeps you small',
      'The specific tension between where you came from and where you are going',
      'What activating your North Node looks like in practical terms this lifetime',
      'The specific fear or resistance that keeps you reaching back to the South Node',
      'The timing of North Node activation windows in your current cycle',
    ],
    guidanceType: 'practical-solution',
    guidanceText: 'A North Node activation guide with the specific first move toward your node and the South Node habit most important to release in your current chapter.',
    upsell: { id: 'soul-contract-reading', name: 'The Soul Contract Reading', price: 47 },
  },
  {
    id: 'personal-year-deep-dive',
    name: 'The Personal Year Deep Dive',
    tagline: 'The full picture of your current Personal Year — what it is asking and offering',
    emoji: '📆',
    price: 29,
    domain: 'life-path',
    isPopular: true,
    isBestSeller: true,
    rating: 4.8,
    reviewCount: 3241,
    deliveryMinutes: 20,
    hook: 'Your Personal Year is not just a number. It is a specific energetic climate with a precise demand and a specific window of opportunity. Most people receive a one-paragraph description of their year and miss the nuance that determines which moves work and which do not.',
    whatYouGet: [
      'Your current Personal Year number and its complete energetic description',
      'The specific demand this year is making of you versus what it is offering',
      'The three months in this year when energy peaks and what to do with them',
      'The two months when action is most likely to meet resistance',
      'The specific type of relationship this year most supports or challenges',
      'The one decision this year that will have the most disproportionate long-term impact',
    ],
    guidanceType: 'practical-solution',
    guidanceText: 'A Personal Year navigation guide with month-by-month energy forecast and the specific move most supported in your current phase.',
    upsell: { id: 'annual-destiny-forecast', name: 'The Annual Destiny Forecast', price: 77 },
  },
  {
    id: 'master-number-reading',
    name: 'The Master Number Reading',
    tagline: 'For 11, 22, and 33 Life Paths — the full weight of what you carry',
    emoji: '✴️',
    price: 47,
    domain: 'life-path',
    isNew: true,
    isFlagship: true,
    rating: 4.9,
    reviewCount: 432,
    deliveryMinutes: 20,
    hook: 'Master numbers are not superior Life Paths. They are high-voltage numbers that come with proportionally higher demands. The 11 must learn to hold vision without collapsing into anxiety. The 22 must build for humanity without losing themselves. The 33 must teach without martyrdom. Most master number readings celebrate the gift without mapping the cost.',
    whatYouGet: [
      'The full expression of your master number, both the high vibration and the shadow',
      'The specific challenge your master number creates that single-digit paths do not face',
      'How your master number interacts with your current Pinnacle phase',
      'The specific way your master number has been expressing through your life so far',
      'What full activation of your master number requires that you have not yet given it',
      'The integration practice for the tension between your master number and its base digit',
    ],
    guidanceType: 'spiritual-remedy',
    guidanceText: 'A master number integration practice for the specific tension between your high vibration potential and your current expression, with daily discipline for sustained high-frequency living.',
    upsell: { id: 'life-path-deep-dive', name: 'The Life Path Deep Dive', price: 57 },
  },
  {
    id: 'expression-number-reading',
    name: 'The Expression Number Reading',
    tagline: 'The natural talents encoded in your full birth name',
    emoji: '🎭',
    price: 29,
    domain: 'life-path',
    rating: 4.7,
    reviewCount: 876,
    deliveryMinutes: 20,
    hook: 'Your full birth name encoded a specific set of talents, abilities, and ways of engaging with the world at the moment you were named. Most people have never had these read in full. The Expression number is the most directly actionable number in your blueprint for career and creative direction — because it describes what comes most naturally, not what you have worked hardest to develop.',
    whatYouGet: [
      'Your Expression number and its complete vocational and creative description',
      'The natural talents your Expression number encodes and how they show up',
      'How your Expression number interacts with your Life Path, where they support versus create tension',
      'The professional environment where your Expression number produces most effectively',
      'The specific gift your Expression number carries that others would most value',
      'How to position your Expression number talents in the market',
    ],
    guidanceType: 'practical-solution',
    guidanceText: 'A talent positioning guide with the specific professional context where your Expression number produces most and the one repositioning move that makes it most visible.',
    upsell: { id: 'life-path-deep-dive', name: 'The Life Path Deep Dive', price: 57 },
  },
  {
    id: 'soul-urge-reading',
    name: 'The Soul Urge Reading',
    tagline: 'What your heart actually wants underneath everything you think you want',
    emoji: '💫',
    price: 29,
    domain: 'life-path',
    isPopular: true,
    rating: 4.8,
    reviewCount: 1654,
    deliveryMinutes: 20,
    hook: 'The Soul Urge is calculated from the vowels of your birth name and describes the deepest motivational current beneath your conscious desires. Most people spend significant energy pursuing what they think they want while this deeper current keeps creating a persistent sense that something is missing — because the surface goal and the soul goal are not the same thing.',
    whatYouGet: [
      'Your Soul Urge number and its complete motivational description',
      'The core desire that drives you beneath all conscious goals and ambitions',
      'How your Soul Urge shapes your relationship choices, career direction, and life satisfaction',
      'The specific way your Soul Urge gets suppressed and what it costs you when it does',
      'Where your Soul Urge and Life Path are in alignment versus tension',
      'How to build a life that satisfies your Soul Urge without abandoning your practical responsibilities',
    ],
    guidanceType: 'spiritual-remedy',
    guidanceText: 'A Soul Urge alignment practice with the specific daily action that most directly nourishes your core motivational current.',
    upsell: { id: 'life-path-deep-dive', name: 'The Life Path Deep Dive', price: 57 },
  },
  {
    id: 'missing-numbers-reading',
    name: 'The Missing Numbers Reading',
    tagline: 'The numbers absent from your chart — and what their absence means',
    emoji: '🔍',
    price: 37,
    domain: 'life-path',
    rating: 4.7,
    reviewCount: 765,
    deliveryMinutes: 20,
    hook: 'What is absent from your chart is as significant as what is present. Missing numbers indicate specific energies that were underdeveloped in previous lifetimes and must be consciously cultivated in this one. They show up as blind spots, inexplicable weaknesses, or areas where effort consistently produces less result than expected.',
    whatYouGet: [
      'Your missing numbers identified from your complete birth blueprint',
      'What each missing number represents as an underdeveloped capacity',
      'How each missing number manifests as a pattern, blind spot, or recurring challenge',
      'The difference between a missing number being worked versus avoided',
      'A specific practice for developing each missing number\'s quality',
      'How your missing numbers interact with your Life Path and Pinnacle',
    ],
    guidanceType: 'spiritual-remedy',
    guidanceText: 'A missing number development guide with specific daily practices for cultivating each absent quality, calibrated to your current cycle and Pinnacle.',
    upsell: { id: 'karmic-lessons-reading', name: 'The Karmic Lessons Reading', price: 37 },
  },
  {
    id: 'numerology-name-reading',
    name: 'The Name Vibration Reading',
    tagline: 'What your name vibrates — and whether it is working for or against you',
    emoji: '📝',
    price: 29,
    domain: 'life-path',
    isPopular: true,
    rating: 4.7,
    reviewCount: 1876,
    deliveryMinutes: 20,
    hook: 'Every name carries a specific vibration. The name you use daily — whether your birth name, a nickname, or a professional name — is either amplifying your natural frequency or creating friction against it. Most people have never had their name\'s vibration assessed against their blueprint. This reading does that with precision.',
    whatYouGet: [
      'Your current name\'s vibrational value and its precise frequency description',
      'Whether your current name aligns with or conflicts with your Life Path',
      'Which life domain your name most amplifies, love, career, health, or spiritual',
      'How your name vibration interacts with your Destiny number',
      'Whether a name adjustment is recommended and specifically why',
      'The principles for choosing a name most aligned with your Life Path',
    ],
    guidanceType: 'practical-solution',
    guidanceText: 'A name vibration assessment with specific recommendations for optimising your name\'s frequency alignment with your Life Path.',
    upsell: { id: 'expression-number-reading', name: 'The Expression Number Reading', price: 29 },
  },
]

export const getLifePathToolById      = (id: string) => lifePathTools.find(t => t.id === id)
export const getPopularLifePathTools  = ()           => lifePathTools.filter(t => t.isPopular)
export const getNewLifePathTools      = ()           => lifePathTools.filter(t => t.isNew)
export const getFlagshipLifePathTools = ()           => lifePathTools.filter(t => t.isFlagship)
