// ============================================================
// LOVE & RELATIONSHIPS — 12 Tools
// Domain: love
// Route: /domain/love-relationships
// Source of truth: tool_registry.py
// ============================================================

export interface LoveTool {
  id: string
  name: string
  tagline: string
  emoji: string
  hook: string
  price: number
  domain: 'love'
  isPopular?: boolean
  isBestSeller?: boolean
  isNew?: boolean
  isFlagship?: boolean
  rating?: number
  reviewCount?: number
  requiresImage?: { type: 'face' | 'palm' | 'both' } | null
  requiresPartner?: boolean
  whatYouGet: string[]
  guidanceType?: 'spiritual-remedy' | 'practical-solution' | 'daily-guidance'
  guidanceText?: string
  upsell?: { id: string; name: string; price: number }
  deliveryMinutes?: number
}

export const loveTools: LoveTool[] = [
  {
    id: 'soulmate-arrival-window',
    name: 'The Soulmate Arrival Window',
    tagline: 'The exact window when your person enters your life',
    emoji: '⌛',
    price: 37,
    domain: 'love',
    isPopular: true,
    isBestSeller: true,
    rating: 4.9,
    reviewCount: 3847,
    deliveryMinutes: 20,
    hook: 'Most people miss their soulmate window not because it closes, but because they did not know it was open. Your Personal Year cycle, Venus timing, and Life Path create specific windows of elevated romantic receptivity. One is opening for you right now.',
    whatYouGet: [
      'Three love windows in the next 24 months with month-precise timing',
      'What kind of person arrives in each window, their name pattern and chart signature',
      'What you must be doing differently in each window to be ready',
      'The one pattern that has been closing your windows early',
      'Whether this year or next is your highest window year',
      'A 21-day opening practice from your ancestral tradition calibrated to your window timing',
    ],
    guidanceType: 'spiritual-remedy',
    guidanceText: 'A 21-day opening practice from your ancestral tradition, specific daily action calibrated to your window timing.',
    upsell: { id: 'love-wound-reading', name: 'The Love Wound Reading', price: 47 },
  },
  {
    id: 'love-wound-reading',
    name: 'The Love Wound Reading',
    tagline: 'Why the same pain keeps returning — named and ended',
    emoji: '💔',
    price: 47,
    domain: 'love',
    isPopular: true,
    rating: 4.9,
    reviewCount: 2341,
    deliveryMinutes: 20,
    hook: 'You have not had five different heartbreaks. You have had one heartbreak five times. The pattern is in your chart, specifically your Heart Line, Venus placement, and karmic debt signature. Once you see it, it cannot repeat.',
    whatYouGet: [
      'The exact repeating pattern across your love history, named and explained',
      'The chart-based and numerical root of the pattern',
      'Which type of person reliably triggers it and why they keep appearing',
      'The karmic origin, what this pattern is here to teach you',
      'A 90-day pattern interruption protocol, specific, practical, and daily',
      'The tradition-calibrated clearing practice for your specific wound type',
    ],
    guidanceType: 'spiritual-remedy',
    guidanceText: 'A tradition-calibrated 90-day pattern interruption practice combining daily actions with a heritage-calibrated spiritual clearing.',
    upsell: { id: 'karmic-love-debt', name: 'The Karmic Love Debt', price: 57 },
  },
  {
    id: 'karmic-love-debt',
    name: 'The Karmic Love Debt',
    tagline: 'The love karma you carried in — and how to complete it',
    emoji: '🔄',
    price: 57,
    domain: 'love',
    isFlagship: true,
    rating: 4.9,
    reviewCount: 876,
    deliveryMinutes: 20,
    hook: 'Some love pain does not originate in this lifetime. Karmic love debts are agreements encoded before you arrived — contracts that draw you toward specific people and specific pain until the underlying lesson is demonstrated and released. This reading names the debt precisely and maps the repayment path.',
    whatYouGet: [
      'Whether karmic love debts are present and where they sit in your chart',
      'The past-life origin story and the soul agreement still active',
      'Who in your current life is karmically contracted with you and what role they play',
      'What completing the love karma looks like in practical terms',
      'The precise lesson the debt is waiting to see you demonstrate',
      'A 40-day karmic resolution protocol, heritage-calibrated for your specific debt type',
    ],
    guidanceType: 'spiritual-remedy',
    guidanceText: 'A karmic love debt resolution protocol, 40 days, combining specific daily practices with a heritage-calibrated spiritual clearing for your debt type.',
    upsell: { id: 'complete-love-synthesis', name: 'The Complete Love Synthesis', price: 97 },
  },
  {
    id: 'twin-flame-verdict',
    name: 'The Twin Flame vs Soulmate Verdict',
    tagline: 'Two names. One honest verdict on what this actually is.',
    emoji: '🔥',
    price: 37,
    domain: 'love',
    isPopular: true,
    requiresPartner: true,
    rating: 4.8,
    reviewCount: 2103,
    deliveryMinutes: 20,
    hook: 'The twin flame label is the most misused concept in modern spirituality. Most twin flame relationships are karmic entanglements or trauma bonds. This reading uses your charts, not your feelings, to give you a specific and honest verdict on what this connection actually is.',
    whatYouGet: [
      'A direct verdict, twin flame, soulmate, karmic contract, or growth relationship',
      'The numerical and chart-based evidence for that verdict',
      'What this connection is here to teach you regardless of its type',
      'Whether reunion or resolution is what the charts support',
      'The specific pattern this relationship is activating in your chart',
      'A navigation guide for the connection type identified',
    ],
    guidanceType: 'practical-solution',
    guidanceText: 'A navigation guide for the specific connection type identified, with the one conversation or inner shift most likely to move it toward its highest potential.',
    upsell: { id: 'complete-love-synthesis', name: 'The Complete Love Synthesis', price: 97 },
  },
  {
    id: 'compatibility-decoder',
    name: 'The Compatibility Decoder',
    tagline: 'Where you are naturally aligned — and where you will collide',
    emoji: '⚖️',
    price: 37,
    domain: 'love',
    requiresPartner: true,
    rating: 4.8,
    reviewCount: 1654,
    deliveryMinutes: 20,
    hook: 'Chemistry is not the whole story. Two people can feel magnetic and be fundamentally incompatible in the domains that sustain a relationship over time. This reading maps where your charts naturally support each other — and where the friction is not situational but structural.',
    whatYouGet: [
      'Compatibility score across 5 key domains, emotional, financial, physical, intellectual, and long-term vision',
      'The area of strongest natural harmony between your charts',
      'The area of guaranteed structural friction and specifically why',
      'The karmic contract between the two people',
      'Whether this is a growth relationship or a harvest relationship',
      'The one communication approach that prevents your most likely conflict pattern',
    ],
    guidanceType: 'practical-solution',
    guidanceText: 'A compatibility navigation guide addressing the structural gap most likely to cause problems, with specific language for the three most common friction points.',
    upsell: { id: 'twin-flame-verdict', name: 'The Twin Flame vs Soulmate Verdict', price: 37 },
  },
  {
    id: 'attachment-pattern-reading',
    name: 'The Attachment Pattern Reading',
    tagline: 'Your attachment style decoded — and what it costs you in love',
    emoji: '🪢',
    price: 47,
    domain: 'love',
    isPopular: true,
    rating: 4.8,
    reviewCount: 1432,
    deliveryMinutes: 20,
    hook: 'Your attachment style is not a personality type. It is a survival strategy your nervous system developed early and your chart confirms. Anxious, avoidant, disorganised, or secure, each pattern leaves a specific signature across your Moon sign, Venus placement, and 4th house.',
    whatYouGet: [
      'Your primary attachment style derived from your chart, not a questionnaire',
      'The early experience your chart indicates created this pattern',
      'How your attachment style shows up in the beginning, middle, and ending of relationships',
      'The specific trigger that activates your attachment wound most reliably',
      'What your nervous system actually needs to feel safe enough to attach securely',
      'A 60-day attachment recalibration practice from your heritage tradition',
    ],
    guidanceType: 'spiritual-remedy',
    guidanceText: 'A 60-day attachment recalibration practice, heritage-calibrated to your specific attachment wound, structured in three phases: recognition, regulation, and re-patterning.',
    upsell: { id: 'love-wound-reading', name: 'The Love Wound Reading', price: 47 },
  },
  {
    id: 'love-timing-forecast',
    name: 'The Love Timing Forecast',
    tagline: 'Your next 12 months in love — month by month',
    emoji: '📅',
    price: 29,
    domain: 'love',
    isPopular: true,
    rating: 4.8,
    reviewCount: 2876,
    deliveryMinutes: 20,
    hook: 'Love does not arrive on a random schedule. Your Personal Year, your Venus timing, and your personal cycle create a specific map of romantic receptivity across any 12-month period. Most people move through peak windows completely unaware — open for connection, but not positioned to receive it.',
    whatYouGet: [
      'Month-by-month love energy map for the next 12 months',
      'Three peak romantic windows with specific preparation instructions for each',
      'Two caution periods when new relationships are likely to be short-lived',
      'What type of connection is most supported in your current cycle',
      'The single action that most opens your romantic field in the next 90 days',
      'How your current Personal Year interacts with your love life specifically',
    ],
    guidanceType: 'practical-solution',
    guidanceText: 'A 12-month love timing guide with specific action for each peak window and specific caution for each low period.',
    upsell: { id: 'soulmate-arrival-window', name: 'The Soulmate Arrival Window', price: 37 },
  },
  {
    id: 'relationship-health-scan',
    name: 'The Relationship Health Scan',
    tagline: 'An honest assessment of where your relationship actually stands',
    emoji: '💚',
    price: 37,
    domain: 'love',
    requiresPartner: true,
    rating: 4.7,
    reviewCount: 987,
    deliveryMinutes: 20,
    hook: 'Most couples know something is off before they can name it. The gap between sensing a problem and being able to articulate it is exactly where most relationships lose ground. This reading uses both charts to identify whether what is off is a temporary cycle, a repeating pattern, or a structural incompatibility — because the answer changes everything about what to do next.',
    whatYouGet: [
      'Relationship health score across 5 domains, connection, communication, intimacy, shared vision, and growth',
      'What is currently most depleting the relationship',
      'What the current timing cycle is asking of the relationship',
      'Whether the current difficulties are temporary or structural',
      'The one shift most likely to restore health to the weakest domain',
      'A 30-day relationship restoration practice calibrated to both charts',
    ],
    guidanceType: 'practical-solution',
    guidanceText: 'A 30-day relationship restoration practice with specific daily actions for the weakest domain identified in the scan.',
    upsell: { id: 'compatibility-decoder', name: 'The Compatibility Decoder', price: 37 },
  },
  {
    id: 'divorce-or-stay-reading',
    name: 'The Divorce or Stay Reading',
    tagline: 'The most important relationship decision you will ever make — clarified',
    emoji: '🔱',
    price: 57,
    domain: 'love',
    isFlagship: true,
    requiresPartner: true,
    rating: 4.9,
    reviewCount: 654,
    deliveryMinutes: 20,
    hook: 'No one should make the decision to stay or leave a long-term relationship based on how they feel on a given Tuesday. Your chart, your partner\'s chart, and the composite between you contain specific information about whether this relationship has completed its contract or whether what feels like an ending is actually a Pinnacle transition.',
    whatYouGet: [
      'Whether the relationship\'s soul contract is complete or still active',
      'What leaving costs you karmically versus what staying costs you energetically',
      'Whether current difficulties are a growth phase or a completion signal',
      'What the charts say about life trajectory for each path, stay or leave',
      'The specific timing indicator that marks when clarity arrives',
      'A decision framework calibrated to both charts and current timing',
    ],
    guidanceType: 'practical-solution',
    guidanceText: 'A decision clarity framework with specific inner and outer conditions that must be met before the decision is made, calibrated to both charts and the current cycle.',
    upsell: { id: 'complete-love-synthesis', name: 'The Complete Love Synthesis', price: 97 },
  },
  {
    id: 'self-love-blueprint',
    name: 'The Self Love Blueprint',
    tagline: 'How your chart describes the love you owe yourself first',
    emoji: '🌸',
    price: 37,
    domain: 'love',
    isNew: true,
    rating: 4.8,
    reviewCount: 432,
    deliveryMinutes: 20,
    hook: 'Every relationship you have ever had reflects the relationship you have with yourself. That is not a self-help aphorism — it is encoded in your chart with the same precision as every other relationship. Your Moon sign describes what you actually need. Your Venus placement describes what you believe you deserve. Most people have never had these two read together, because the gap between them is where all the work lives.',
    whatYouGet: [
      'Your emotional self-care needs from your Moon sign in plain language',
      'How your Venus placement shapes your self-worth and what you believe you deserve',
      'The specific self-abandonment pattern most active in your chart',
      'What genuine self-love looks like for your specific design versus generic advice',
      'The practice from your heritage tradition most calibrated to your self-love wound',
      'How developing self-love changes your magnetic field and who you attract',
    ],
    guidanceType: 'spiritual-remedy',
    guidanceText: 'A self-love practice from your heritage tradition, structured as a 30-day daily commitment calibrated to your Moon sign and Venus placement.',
    upsell: { id: 'attachment-pattern-reading', name: 'The Attachment Pattern Reading', price: 47 },
  },
  {
    id: 'ex-return-oracle',
    name: 'The Ex Return Oracle',
    tagline: 'Whether they are coming back — and whether you should want them to',
    emoji: '🔮',
    price: 29,
    domain: 'love',
    isPopular: true,
    rating: 4.7,
    reviewCount: 3241,
    deliveryMinutes: 20,
    hook: 'The question of whether an ex will return is almost never the real question. The real question is whether the return would serve your highest path or simply repeat the pattern. Your chart knows the difference even when your heart does not.',
    whatYouGet: [
      'What the timing indicators currently say about a reconnection window',
      'Whether the karmic contract between you is complete or still has unfinished business',
      'What a return would likely look like based on both charts',
      'Whether your current Personal Year supports rekindling or completing',
      'The honest answer to whether a return serves your growth or your wound',
      'What to do with the energy of this connection regardless of outcome',
    ],
    guidanceType: 'practical-solution',
    guidanceText: 'A clarity guide for the specific situation, with the one inner shift that changes the dynamic regardless of whether they return.',
    upsell: { id: 'love-wound-reading', name: 'The Love Wound Reading', price: 47 },
  },
  {
    id: 'love-language-blueprint',
    name: 'The Love Language Blueprint',
    tagline: 'How you give love, how you need to receive it, and the gap between them',
    emoji: '💝',
    price: 19,
    domain: 'love',
    isPopular: true,
    isBestSeller: true,
    rating: 4.8,
    reviewCount: 5231,
    deliveryMinutes: 20,
    hook: 'The five love languages are a useful starting point — but a starting point is not a map. Your chart describes how you give and receive love with a precision no questionnaire can match, including the specific way your love expression shifts when you feel secure versus when you feel anxious. Those two are almost always completely different.',
    whatYouGet: [
      'Your primary love language derived from your Venus placement and Moon sign',
      'How you express love when feeling secure versus when feeling anxious',
      'Your partner\'s most likely love language type from their birth date',
      'The specific gap between how you give and how you need to receive',
      'Why generic love language advice often makes things worse for your type',
      'Three specific daily practices that close the love language gap',
    ],
    guidanceType: 'practical-solution',
    guidanceText: 'A love language alignment guide with three specific daily practices that close the gap between giving and receiving for your chart type.',
    upsell: { id: 'attachment-pattern-reading', name: 'The Attachment Pattern Reading', price: 47 },
  },
]

export const getLoveToolById      = (id: string) => loveTools.find(t => t.id === id)
export const getPopularLoveTools  = ()           => loveTools.filter(t => t.isPopular)
export const getNewLoveTools      = ()           => loveTools.filter(t => t.isNew)
export const getFlagshipLoveTools = ()           => loveTools.filter(t => t.isFlagship)
