// ============================================================
// OMNI-SEER — 29 Tools (restructured from the original 78)
// Domain: oracle-temple
// Route: /domain/omni-seer
// Flagship tier. Restructured per the confirmed plan: 6 exact
// duplicates of base-domain tools cut, all 9 face+palm combination
// tools cut entirely (face and palm are permanently separate
// tracks here), overlapping "complete portrait" tools collapsed
// into one true flagship. Pricing sits at the top of the catalog
// band ($49-99) since this tier is meant to be genuinely more
// comprehensive, not just more expensive.
// ============================================================

export interface OmniSeerTool {
  id: string
  name: string
  tagline: string
  emoji: string
  hook: string
  price: number
  domain: 'oracle-temple'
  requiresPartner?: boolean
  isPopular?: boolean
  isBestSeller?: boolean
  isNew?: boolean
  rating?: number
  reviewCount?: number
  whatYouGet: string[]
  guidanceType?: 'practical-solution' | 'daily-guidance'
  guidanceText?: string
}

export const omniTools: OmniSeerTool[] = [

  // ── Love (3) ──────────────────────────────────────────────
  {
    id: 'complete-love-synthesis',
    name: 'The Full Weight of How You Love',
    tagline: 'The complete synthesis of your love life across every discipline, not a single-angle reading',
    emoji: '❤️‍🔥',
    price: 79,
    domain: 'oracle-temple',
    isBestSeller: true,
    rating: 4.9,
    reviewCount: 2341,
    hook: 'A single-angle reading catches one facet of how you love. This one catches all of them at once, the pattern, the timing, the wound, the want, synthesized into a single coherent picture instead of separate fragments you have to piece together yourself. It is the difference between a photograph and the full shape of the thing being photographed.',
    whatYouGet: [
      'Your complete relationship pattern, synthesized across every relevant angle rather than one',
      'How your core wound, your timing, and your actual want all connect to each other',
      'The single throughline running underneath every relationship you have had',
      'Where the different angles of this synthesis agree, which is where the real signal is',
      'Where they genuinely disagree, and what that tension itself is telling you',
      'What this synthesis reveals that no single-focus reading could have surfaced alone',
      'A clear read on where you are right now, relative to your own longer pattern',
      'What meaningfully shifting this pattern would actually require',
      'The kind of connection most likely to interrupt the pattern in a good way',
    ],
  },
  {
    id: 'soulmate-compatibility-verdict',
    name: 'Two Names, One Verdict',
    tagline: 'A direct verdict on soulmate compatibility, built from both of your complete details',
    emoji: '💍',
    price: 69,
    domain: 'oracle-temple',
    requiresPartner: true,
    rating: 4.8,
    reviewCount: 1567,
    hook: 'This is not a percentage score. It is a direct, synthesized verdict on whether this is a genuine soulmate connection, built from both of your complete details rather than a single compatibility angle, with the reasoning shown, not just the answer.',
    whatYouGet: [
      'A direct verdict on soulmate compatibility, not a vague percentage',
      'The full reasoning behind that verdict, synthesized across every relevant angle',
      'Where the two of you align at a level deeper than day-to-day compatibility',
      'The one thing most likely to test this connection, named honestly',
      'What this specific pairing is actually built to accomplish together',
      'How this verdict compares to a standard single-angle compatibility reading',
      'What staying, based on this verdict, would genuinely ask of both of you',
      'A clear answer to whether the timing is right for this connection to deepen now',
    ],
  },
  {
    id: 'professional-compatibility-scan',
    name: 'Before You Sign Anything',
    tagline: 'A compatibility reading built specifically for business partners, not romantic ones',
    emoji: '🤝',
    price: 69,
    domain: 'oracle-temple',
    requiresPartner: true,
    rating: 4.7,
    reviewCount: 892,
    hook: 'Romantic compatibility and professional compatibility are not the same question, and reading one as if it answers the other has cost people real money. This scan is built specifically for a business partnership: where the working styles genuinely complement each other, and where the friction is structural rather than personal.',
    whatYouGet: [
      'A direct read on professional, not romantic, compatibility between the two of you',
      'Where your working styles genuinely complement each other',
      'The specific friction points most likely to surface under real business pressure',
      'Which of those friction points are workable and which are structural',
      'The kind of role split most likely to let this partnership actually work',
      'A honest read on how this pairing handles disagreement under pressure',
      'What this partnership is genuinely strong at, together, that neither could do alone',
      'What to put in writing now, before it becomes necessary later',
    ],
  },

  // ── Wealth (4) ────────────────────────────────────────────
  {
    id: 'complete-wealth-synthesis',
    name: 'Everything Your Money Is Trying to Tell You',
    tagline: 'The complete synthesis of your financial pattern, across every discipline at once',
    emoji: '💰',
    price: 79,
    domain: 'oracle-temple',
    isBestSeller: true,
    rating: 4.9,
    reviewCount: 2103,
    hook: 'Your earning pattern, your specific blocks, your natural timing, and your actual capacity for risk rarely get read together, even though they are constantly interacting with each other in every real financial decision you make. This reading synthesizes all of it into one coherent financial portrait instead of four separate, disconnected readings.',
    whatYouGet: [
      'Your complete financial pattern, synthesized across every relevant discipline',
      'How your earning style, your specific blocks, and your risk capacity interact',
      'The single throughline connecting your financial history to where you are now',
      'Where the different angles of this synthesis agree, and where the real signal is',
      'The specific financial ceiling in your pattern, and what actually breaks it',
      'The kind of wealth-building path genuinely built for your particular pattern',
      'What this synthesis reveals that no single-angle financial reading could catch',
      'The real window ahead for your next significant financial move',
      'What meaningfully shifting your financial trajectory would actually require',
    ],
  },
  {
    id: 'business-destiny-synthesis',
    name: 'Your Business, Fully Mapped',
    tagline: 'A full synthesis of your business, its trajectory, and what it is actually built to become',
    emoji: '🏢',
    price: 79,
    domain: 'oracle-temple',
    rating: 4.8,
    reviewCount: 1432,
    hook: 'A business carries a pattern of its own, separate from the pattern of the person running it, and reading only one of the two leaves half the picture missing. This synthesis reads both: your pattern as an owner, and the business itself, showing where they support each other and where they are quietly working at cross purposes.',
    whatYouGet: [
      'The business\'s own pattern, read as distinct from your pattern as its owner',
      'Where your pattern and the business\'s pattern support each other',
      'Where they are quietly working at cross purposes, undermining growth',
      'The specific trajectory this business is actually built to follow',
      'The point where this business is most likely to plateau, and what moves it past that point',
      'What sustainable growth looks like for a business shaped like this one',
      'Whether this business is built to be sold, scaled, or run for the long term',
      'The single decision most likely to determine which of those three paths it takes',
      'What the next twelve months should actually focus on',
    ],
  },
  {
    id: 'wealth-timing-oracle',
    name: 'The Five-Year Money Forecast',
    tagline: 'A five-year financial forecast, built for long-range decisions rather than the next few months',
    emoji: '📈',
    price: 59,
    domain: 'oracle-temple',
    rating: 4.7,
    reviewCount: 987,
    hook: 'Some financial decisions only make sense against a longer horizon than most forecasts bother to cover. This one maps five years ahead: the strongest windows for major moves, the years that favor consolidation over expansion, and the single point in the timeline where the most significant shift is likely.',
    whatYouGet: [
      'The five-year shape of your financial trajectory, year by year',
      'The strongest windows within that timeline for a major financial move',
      'The years that favor consolidation over expansion, named clearly',
      'The single most significant turning point across the full five years',
      'What to watch for in the year just before that turning point arrives',
      'How this five-year view changes what a near-term decision should actually optimize for',
      'The realistic range of outcomes if the strongest windows are used well',
    ],
  },
  {
    id: 'personal-brand-frequency',
    name: "The Brand You're Already Becoming",
    tagline: "A reading of the personal brand you're already building, whether or not you've noticed it forming",
    emoji: '🎯',
    price: 59,
    domain: 'oracle-temple',
    hook: 'A personal brand is forming around you already, built from how you actually show up rather than what you intend, and it is often quite different from the version you think you are projecting. This reading names what is actually forming, where it is working for you, and where it is quietly working against you.',
    whatYouGet: [
      'The personal brand actually forming around you, as distinct from the one you intend',
      'Where this brand is genuinely working in your favor',
      'Where it is quietly working against you, without your noticing',
      'The specific gap between how you intend to be seen and how you are actually perceived',
      'The kind of audience or opportunity this brand naturally attracts',
      'The kind it naturally repels, and whether that is a problem worth solving',
      'One deliberate shift that would close the gap most effectively',
    ],
  },

  // ── Health (1) ────────────────────────────────────────────
  {
    id: 'complete-health-synthesis',
    name: 'The Full Read on Your Body',
    tagline: 'A full synthesis of your physical constitution across every relevant discipline, in one reading',
    emoji: '🌿',
    price: 79,
    domain: 'oracle-temple',
    isBestSeller: true,
    rating: 4.9,
    reviewCount: 1876,
    hook: 'Generic health advice fails your specific body because it was never built for it. This synthesis reads your physical constitution across every relevant discipline at once, converging on the same picture from multiple directions, so what you get is not one framework\'s opinion but the intersection of several independent ones confirming the same thing.',
    whatYouGet: [
      'Your complete physical constitution, synthesized across every relevant discipline',
      'Where multiple independent readings of your body converge on the same conclusion',
      'What genuinely supports your specific constitution, distinct from trending health advice',
      'What quietly works against it, even when marketed as universally healthy',
      'The specific area of your body most affected by unmanaged stress, and how it shows up',
      'What real rest looks like for your constitution, as opposed to the generic version',
      'The pattern connecting your energy levels to your actual daily choices, made visible',
      'One realistic, sustainable adjustment that would meaningfully change how you feel',
      'What this synthesis reveals that no single-discipline health reading could catch alone',
    ],
  },

  // ── Purpose & Spiritual (4) ───────────────────────────────
  {
    id: 'complete-spiritual-synthesis',
    name: 'Everything Beneath the Surface',
    tagline: 'A full spiritual synthesis, going beneath the surface of any single-discipline reading',
    emoji: '🕯️',
    price: 79,
    domain: 'oracle-temple',
    rating: 4.8,
    reviewCount: 1543,
    hook: 'Your spiritual pattern rarely fits inside one framework cleanly, and reading it through only one lens leaves real parts of the picture in shadow. This synthesis reads it through several at once: what you carried in, what you are here to complete, and what has been quietly running beneath your conscious awareness the entire time.',
    whatYouGet: [
      'Your complete spiritual pattern, synthesized across multiple disciplines at once',
      'What you most likely carried into this life, and how it is shaping the one you are living',
      'The specific thing you are here to complete, named directly rather than abstractly',
      'What has been running beneath your conscious awareness, now brought into view',
      'Where different spiritual frameworks converge on the same conclusion about you',
      'The practice most aligned with your specific pattern, not a generic recommendation',
      'What genuine spiritual progress actually looks like for someone shaped like you',
      'What this synthesis reveals that no single-framework spiritual reading could catch',
      'The next real threshold ahead in your spiritual development',
    ],
  },
  {
    id: 'complete-purpose-synthesis',
    name: "The Whole Reason You're Here",
    tagline: "A full synthesis of your life's purpose, built from every relevant discipline at once",
    emoji: '🔥',
    price: 79,
    domain: 'oracle-temple',
    isPopular: true,
    rating: 4.9,
    reviewCount: 2287,
    hook: 'Purpose readings that rely on a single discipline tend to produce something either too vague to act on or too narrow to be true. This synthesis triangulates your purpose from multiple independent angles at once, converging on something specific enough to actually live by.',
    whatYouGet: [
      'Your life purpose, synthesized from multiple independent disciplines at once',
      'Where those disciplines converge, which is where the real signal is',
      'What has likely been mistaken for purpose, but is actually a substitute for it',
      'The specific gap between what you know about your purpose and how you are living',
      'What living it, rather than only knowing it, would concretely require',
      'The environment where this purpose is genuinely supported, and where it quietly withers',
      'The fear most likely to have kept this purpose at arm\'s length so far',
      'What this synthesis reveals that no single-discipline purpose reading could catch',
      'One decision in the next month that would meaningfully close the gap',
    ],
  },
  {
    id: 'pattern-breaker',
    name: 'The Pattern You Keep Living',
    tagline: 'A reading that names the specific pattern you keep living out, and what actually breaks it',
    emoji: '⛓️',
    price: 69,
    domain: 'oracle-temple',
    rating: 4.8,
    reviewCount: 1298,
    hook: 'Some patterns are karmic in origin, carried forward until they are genuinely resolved rather than merely repeated. This reading names your specific pattern, what you actually owe, in the sense of unfinished business rather than punishment, and what completing it, instead of continuing to repeat it, would actually look like.',
    whatYouGet: [
      'The specific pattern you keep living out, named clearly across multiple areas of your life',
      'The unfinished business this pattern represents, distinct from a punishment narrative',
      'Where this pattern shows up most persistently, and why that area specifically',
      'The difference between resolving this pattern and merely surviving it again',
      'What resolution would actually look like, practically, not only spiritually',
      'The kind of situation most likely to offer a genuine chance to break it',
      'How you will know, concretely, that it has actually been resolved',
    ],
  },
  {
    id: 'creative-genius-synthesis',
    name: "The Genius You Haven't Used Yet",
    tagline: "A reading of the specific creative capacity you haven't fully used yet, and why",
    emoji: '🎨',
    price: 59,
    domain: 'oracle-temple',
    hook: 'Genuine creative capacity often goes unused, not from a lack of talent but from a lack of permission, sometimes self-imposed, sometimes inherited from somewhere else entirely. This reading names your specific creative capacity, what has been withholding permission to use it, and what actually using it would look like in ordinary life.',
    whatYouGet: [
      'Your specific creative capacity, named clearly rather than generically',
      'What has been withholding permission to use it, named directly',
      'Where this capacity has already leaked out in small, unacknowledged ways',
      'What using it fully would look like in ordinary life, not a dramatic reinvention',
      'The kind of creative work most aligned with this particular capacity',
      'The audience or context most likely to actually receive it well',
      'One small, concrete way to begin using it more fully this month',
    ],
  },

  // ── Family (4) ────────────────────────────────────────────
  {
    id: 'family-destiny-synthesis',
    name: 'What Your Family Actually Passed Down',
    tagline: 'A full synthesis of what your family line actually passed down to you, named clearly',
    emoji: '🌳',
    price: 69,
    domain: 'oracle-temple',
    rating: 4.7,
    reviewCount: 1109,
    hook: 'Every family passes down more than physical resemblance: patterns of conflict, patterns of silence, patterns of who is allowed to succeed and who quietly is not. This synthesis names what your specific family line actually passed down, across every relevant angle, and what carrying it forward differently would look like.',
    whatYouGet: [
      'The specific pattern your family line has passed down, synthesized across multiple angles',
      'Where this pattern shows up most clearly across different generations',
      'The unspoken rule in your family that this pattern has been quietly enforcing',
      'How this pattern has shaped your own choices, often without your full awareness',
      'What has been protecting the family by keeping this pattern in place',
      'What carrying it forward differently, rather than repeating it exactly, would look like',
      'How you would know the pattern has genuinely shifted, not just gone quiet for now',
      'What this synthesis reveals that a single-discipline family reading could not catch',
    ],
  },
  {
    id: 'child-blueprint',
    name: 'Who This Child Is Becoming',
    tagline: 'A reading built for a child, showing who they are becoming rather than who they should be',
    emoji: '🧒',
    price: 59,
    domain: 'oracle-temple',
    rating: 4.8,
    reviewCount: 1432,
    hook: 'Most guidance for raising a child comes from generic developmental milestones that say very little about who this specific child actually is. This reading names your child\'s particular pattern: what they genuinely need to thrive, and where well-intentioned generic parenting advice might actually work against them.',
    whatYouGet: [
      'Your child\'s specific pattern, named clearly rather than filed into a generic stage',
      'What this child genuinely needs to thrive, distinct from standard parenting advice',
      'Where common parenting approaches might actually work against this particular pattern',
      'The environment where this child is most likely to flourish',
      'The kind of encouragement that will land, and the kind that will not',
      'A challenge this child is likely to face, named early enough to prepare for it',
      'What this child is naturally gifted at, even if it has not been obvious yet',
    ],
  },
  {
    id: 'parent-child-relationship-mirror',
    name: "The Conflict That Isn't About Either of You",
    tagline: 'A reading of a parent-child dynamic, showing what is actually driving the friction',
    emoji: '🪞',
    price: 59,
    domain: 'oracle-temple',
    hook: 'Parent-child friction often has less to do with either person individually than with how their two patterns interact with each other. This reading names that interaction specifically: where the two patterns clash structurally, and what would actually ease the friction, as opposed to advice aimed at just one side of it.',
    whatYouGet: [
      'How the parent\'s pattern and the child\'s pattern specifically interact',
      'Where the friction is structural, built into the interaction, rather than either person\'s fault',
      'The situation most likely to trigger this specific friction',
      'What would actually ease it, addressing the interaction rather than just one side',
      'Where the two patterns genuinely complement each other, often overlooked amid the friction',
      'What each side is actually asking for underneath the surface conflict',
      'One shift, on either side, most likely to meaningfully change the dynamic',
    ],
  },
  {
    id: 'fertility-soul-synthesis',
    name: 'When Both Are Ready',
    tagline: 'A reading of the timing question around conception, built from both partners\' details',
    emoji: '🌱',
    price: 69,
    domain: 'oracle-temple',
    requiresPartner: true,
    hook: 'The question of timing around conception involves two people\'s patterns, not one, and reading only one side of it leaves half the picture missing. This synthesis reads both of your patterns together: the windows that favor conception, and what each of you individually might need before that window is fully open.',
    whatYouGet: [
      'The windows ahead that most favor conception, built from both partners\' patterns',
      'What each partner individually might need before that window is fully open',
      'How the two patterns interact specifically around this particular question',
      'The difference between readiness in timing and readiness in the relationship itself',
      'What to expect emotionally in the months leading up to the strongest window',
      'One thing worth addressing together before actively trying',
    ],
  },

  // ── Physical: face and palm, always separate (7) ─────────
  {
    id: 'complete-face-reading',
    name: 'Everything Your Face Has Been Saying',
    tagline: 'A complete face reading covering every relevant feature in one deep synthesis, not nine separate ones',
    emoji: '👤',
    price: 69,
    domain: 'oracle-temple',
    isBestSeller: true,
    rating: 4.8,
    reviewCount: 1654,
    hook: 'Reading one facial feature at a time produces nine thin, disconnected observations instead of one coherent picture. This reading covers every relevant feature together, the shape, the structure, the expression that has settled into place over years, synthesized into a single deep reading instead of fragments.',
    whatYouGet: [
      'A complete reading of your facial structure, shape, and settled expression, read together',
      'What your overall facial structure indicates about your natural temperament',
      'What your habitual expression reveals that you may not consciously notice about yourself',
      'How the different features of your face align, or interestingly do not, on the same traits',
      'The specific quality your face most reliably communicates to strangers, before you speak',
      'What this reading catches that a single-feature reading would have missed entirely',
      'How your face has changed over time in ways that reflect genuine internal change',
      'What this synthesis suggests about how you are actually perceived versus how you intend to be',
    ],
  },
  {
    id: 'life-line-reading',
    name: 'The Life Line Reading',
    tagline: 'A reading of your life line specifically, covering vitality and physical constitution',
    emoji: '🖐️',
    price: 49,
    domain: 'oracle-temple',
    hook: 'The life line is read specifically for vitality and physical constitution, distinct from every other line on the hand. This reading names what yours indicates about your natural stamina, the periods of life where your vitality is strongest, and what genuinely supports it.',
    whatYouGet: [
      'What your life line specifically indicates about your natural vitality and stamina',
      'The periods of life where this line suggests your vitality runs strongest',
      'What genuinely supports your constitution, based on this specific reading',
      'Any notable markers along the line, and what they traditionally indicate',
      'How this reading compares to your general sense of your own energy over the years',
      'One practical takeaway for working with your vitality rather than against it',
    ],
  },
  {
    id: 'heart-line-love-map',
    name: 'The Heart Line, Confirmed Twice',
    tagline: 'Your capacity for love, confirmed across two independent physical markers',
    emoji: '💗',
    price: 54,
    domain: 'oracle-temple',
    rating: 4.7,
    reviewCount: 876,
    hook: 'Two separate physical markers are traditionally read for capacity in love: the heart line itself, and a specific area at the base of the thumb associated with warmth and vitality in relationships. Reading them together, rather than just one, is what actually confirms the pattern instead of leaving it to a single data point.',
    whatYouGet: [
      'What your heart line specifically indicates about your capacity for love',
      'What the corresponding area at the base of your thumb confirms or complicates about that reading',
      'Where these two markers agree, which is where the real signal is',
      'Where they diverge, and what that divergence itself suggests',
      'The pattern in how you tend to give love, based on both markers together',
      'What genuinely deepens your capacity here, versus what has been draining it',
      'How this reading compares to your own lived experience of loving and being loved',
    ],
  },
  {
    id: 'head-line-mind-map',
    name: 'The Head Line Mind Map',
    tagline: 'A reading of your head line, covering how you think and process',
    emoji: '🧠',
    price: 49,
    domain: 'oracle-temple',
    hook: 'The head line is read for how you think and process information, distinct from emotional or physical readings elsewhere on the hand. This reading names your specific thinking style: how you actually reach conclusions, and where that style is a genuine strength versus where it works against you.',
    whatYouGet: [
      'What your head line specifically indicates about your thinking and decision-making style',
      'How you actually tend to reach conclusions, based on the shape and depth of this line',
      'Where this thinking style is a genuine strength',
      'Where it is more likely to work against you, particularly under pressure',
      'How this style compares to how you have always assumed you think',
      'One practical way to work with this style rather than fight it',
    ],
  },
  {
    id: 'fate-line-mission-reading',
    name: 'The Fate Line, Confirmed Twice',
    tagline: 'Your direction and ambition, confirmed across two independent physical markers',
    emoji: '🧭',
    price: 54,
    domain: 'oracle-temple',
    rating: 4.7,
    reviewCount: 743,
    hook: 'Direction and ambition are traditionally read from two separate places: the fate line running through the palm, and a specific area associated with drive and leadership near the base of the index finger. Reading both together confirms the pattern instead of relying on one line alone.',
    whatYouGet: [
      'What your fate line specifically indicates about your life direction',
      'What the corresponding area near your index finger confirms about ambition and drive',
      'Where these two markers agree, which is where the real signal is',
      'Where they diverge, and what that divergence suggests about unresolved tension',
      'The specific kind of direction this combined reading points toward',
      'What has likely been diverting you from this direction so far',
      'What genuinely realigning with it would practically require',
    ],
  },
  {
    id: 'marriage-line-reading',
    name: 'The Marriage Line Reading',
    tagline: 'A reading of your marriage line specifically, covering partnership and commitment',
    emoji: '💍',
    price: 49,
    domain: 'oracle-temple',
    hook: 'The marriage line is read specifically for partnership and long-term commitment, a distinct tradition from the heart line\'s broader reading of love. This reading names what yours indicates about your capacity and pattern for lasting partnership specifically.',
    whatYouGet: [
      'What your marriage line specifically indicates about long-term partnership',
      'How this reading differs from what your heart line indicates about love more broadly',
      'Any notable markers along the line, and what they traditionally suggest',
      'What this reading suggests about your pattern in commitment specifically',
      'How this compares to your own lived experience of long-term partnership',
      'One practical takeaway for approaching commitment from this pattern\'s strengths',
    ],
  },
  {
    id: 'thumb-willpower-reading',
    name: 'The Thumb Willpower Reading',
    tagline: 'A reading of your thumb, covering willpower and follow-through',
    emoji: '👍',
    price: 49,
    domain: 'oracle-temple',
    hook: 'The thumb is read specifically for willpower and follow-through, a distinct tradition from the lines that cover emotion and thought elsewhere on the hand. This reading names what your thumb\'s shape and flexibility traditionally indicate about your capacity to see things through.',
    whatYouGet: [
      'What your thumb\'s shape and flexibility traditionally indicate about willpower',
      'Your natural pattern for follow-through once you have started something',
      'Where this capacity is genuinely strong',
      'Where it is more likely to falter, and under what kind of pressure',
      'How this compares to your own lived experience of finishing what you start',
      'One practical way to work with this pattern rather than fight it',
    ],
  },

  // ── Timing & Destiny (4) ──────────────────────────────────
  {
    id: 'annual-destiny-forecast',
    name: 'The Annual Destiny Forecast',
    tagline: 'A complete annual forecast synthesized across every relevant discipline',
    emoji: '🔮',
    price: 69,
    domain: 'oracle-temple',
    rating: 4.8,
    reviewCount: 1321,
    hook: 'A forecast built from a single discipline only ever tells part of the story of a year. This one synthesizes several at once, converging on the same themes from multiple directions, so what you get is not one framework\'s guess but the intersection of several independently confirming the same shape.',
    whatYouGet: [
      'Your complete year ahead, synthesized across multiple independent disciplines',
      'Where those disciplines converge on the same theme, which is where the real signal is',
      'The single most significant window in the year ahead, confirmed from more than one angle',
      'What this year is genuinely building toward, beneath its surface events',
      'The stretch that calls for rest or consolidation, named across multiple readings',
      'What this synthesis reveals that a single-discipline annual forecast could not catch',
      'The best use of the months remaining in this specific year',
      'How this year connects to the larger arc you are currently moving through',
    ],
  },
  {
    id: 'relocation-power-map',
    name: "Where You're Meant to Be",
    tagline: "A reading of where you're actually built to live, based on your complete details",
    emoji: '🗺️',
    price: 59,
    domain: 'oracle-temple',
    hook: 'Where you live shapes more of your life than most people account for when making the decision. This reading names the kind of place, not necessarily a specific city, but a genuine type of environment, where your particular pattern is most likely to thrive, and where it has likely been quietly working against you.',
    whatYouGet: [
      'The kind of environment where your particular pattern is most likely to thrive',
      'What about your current location may be working against your pattern, if anything',
      'The specific qualities to look for in a place, rather than a single named city',
      'How your relationship to home and place has shaped decisions you did not connect to it',
      'What moving, if it is genuinely warranted, would likely change for you',
      'What staying, and adjusting your relationship to your current place instead, could also achieve',
      'The timing question: whether now is a window that favors a genuine move',
    ],
  },
  {
    id: 'birthday-blueprint',
    name: 'The Day You Were Born, Decoded',
    tagline: 'A complete reading of what your exact birth date encodes, decoded in full',
    emoji: '🎂',
    price: 59,
    domain: 'oracle-temple',
    hook: 'Your exact birth date carries a specific signature that shapes far more than a single birthday reading usually covers, extending into how this signature plays out in your work, not only in a personal sense. This reading decodes it fully, including what it suggests about the kind of work and direction most aligned with it.',
    whatYouGet: [
      'The complete signature encoded in your exact birth date, decoded in full',
      'How this signature shows up in your personal pattern day to day',
      'What it suggests about the kind of work most aligned with your nature',
      'The specific gift this signature carries, that you may have underused',
      'What tends to renew and refresh you around your birthday specifically, each year',
      'How this signature is likely to be misunderstood by people who do not share it',
      'What fully living into this signature, rather than only knowing about it, would look like',
    ],
  },
  {
    id: 'decision-window',
    name: 'The Decision Window',
    tagline: 'A reading built for a specific decision, showing the real window for making it well',
    emoji: '⏳',
    price: 59,
    domain: 'oracle-temple',
    isNew: true,
    hook: 'Some decisions land differently depending on the exact week they are made, no matter how sound the reasoning behind them. This reading is built around one specific decision you bring to it: the real window ahead for making it well, and the signs that the timing has shifted in either direction.',
    whatYouGet: [
      'A direct read on whether now is a genuinely good window for this specific decision',
      'The real window ahead, if now is not it, and what changes once it opens',
      'What is different about a well-timed version of this decision versus a rushed one',
      'The sign that would indicate the window is closing, so it does not get missed',
      'What to have in place before acting, specific to this particular decision',
      'The kind of pressure most likely to push you toward acting too early',
      'What waiting, if that turns out to be the right call, would actually cost versus save',
    ],
  },

  // ── The True Flagship (2) ─────────────────────────────────
  {
    id: 'complete-life-portrait',
    name: 'The Whole of You',
    tagline: 'The single most comprehensive reading in the catalog, synthesizing everything into one complete portrait',
    emoji: '☀️',
    price: 99,
    domain: 'oracle-temple',
    isBestSeller: true,
    isPopular: true,
    rating: 5.0,
    reviewCount: 1876,
    hook: 'This is the reading built to hold everything else at once: your core pattern, your relationships, your work, your inner life, synthesized into a single, coherent portrait rather than a stack of separate readings you have to assemble yourself. It is the most complete picture this platform is able to produce.',
    whatYouGet: [
      'Your complete pattern, synthesized across every major discipline this platform offers',
      'How your relationships, your work, and your inner life connect to a single underlying pattern',
      'The one throughline running underneath everything else in your life',
      'Where every angle of this synthesis agrees, which is where the deepest signal is',
      'The specific tension, if any, between how you appear and who you actually are',
      'What this portrait reveals that no single-domain reading could have surfaced alone',
      'A clear read on exactly where you stand right now, relative to your own larger arc',
      'The single most significant window currently open in your life, across every domain',
      'What genuinely living in alignment with this whole portrait would actually require',
      'A living document you can return to as your life continues to unfold',
    ],
  },
  {
    id: 'complete-union-blueprint',
    name: 'What You Become Together',
    tagline: 'A full two-person synthesis of what this specific pairing becomes together, beyond either person alone',
    emoji: '💞',
    price: 99,
    domain: 'oracle-temple',
    requiresPartner: true,
    isBestSeller: true,
    rating: 4.9,
    reviewCount: 1432,
    hook: 'Two people together create something that is genuinely distinct from either person alone, an entity with its own pattern, its own strengths, and its own particular risks. This reading synthesizes both of your complete details into a portrait of that third thing, the union itself, rather than stopping at how compatible the two of you happen to be.',
    whatYouGet: [
      'A complete synthesis of what this specific union becomes, distinct from either partner alone',
      'The particular strengths this pairing has access to only when combined',
      'The specific risk this union carries that neither partner carries individually',
      'Where each partner\'s pattern completes something the other is missing',
      'The single most significant challenge this specific union is likely to face',
      'What this union is genuinely built to accomplish together, beyond staying together',
      'The long-range shape of this partnership, not just its current chemistry',
      'What each of you would need to bring for this union to reach its full potential',
      'A living document both partners can return to as the relationship continues to unfold',
    ],
  },

]

export const getOmniToolById = (id: string) => omniTools.find(t => t.id === id)
export const getPopularOmniTools = () => omniTools.filter(t => t.isPopular)
