// ============================================================
// OMNI-SEER — PHYSICAL & TIMING (14 tools)
// Domain: oracle-temple
// Route: /domain/omni-seer
// Split out of the original single omni-seer-tools.ts (35 tools)
// for manageability. This file: all face/palm image-based
// tools (10) and Timing & Destiny (4). Every requiresImage
// tool lives here.
// ============================================================

export interface OmniSeerTool {
  id: string
  name: string
  tagline: string
  emoji: string
  hook: string
  price: number
  domain: 'oracle-temple'
  requiresPartner?: boolean
  requiresImage?: { type: 'face' | 'palm' | 'both' }
  isPopular?: boolean
  isBestSeller?: boolean
  isNew?: boolean
  rating?: number
  reviewCount?: number
  whatYouGet: string[]
  guidanceType?: 'practical-solution' | 'daily-guidance'
  guidanceText?: string
  upsell?: { id: string; name: string; price: number }
}

export const omniPhysicalTimingTools: OmniSeerTool[] = [
  {
    id: 'complete-face-reading',
    requiresImage: { type: 'face' },
    name: 'Everything Your Face Has Been Saying',
    tagline: 'A complete face reading covering every relevant feature in one deep synthesis, not nine separate ones',
    emoji: '👤',
    price: 69,
    domain: 'oracle-temple',
    isBestSeller: true,
    rating: 4.8,
    reviewCount: 1654,
    hook: 'Reading one facial feature at a time misses the whole picture. This reading checks every feature together, and shows what it reveals.',
    whatYouGet: [
      'A full check of your face shape, structure, and natural expression, read together',
      'What your overall face structure says about your natural temperament',
      'What your natural expression reveals that you may not notice about yourself',
      'Where your different features agree, or interestingly do not, on the same traits',
      'The one quality your face most reliably shows strangers, before you speak',
      'What this check finds that looking at one feature alone would miss',
      'Whether your face shows more of your father\'s traits or your mother\'s, in the areas linked to each',
      'How your face has changed over time in ways that reflect real inner change',
      'The one feature most likely to be misread by people who do not know you well',
      'What this reading confirms about you that photos alone tend to flatten or miss',
    ],
    upsell: { id: 'health-scribe', name: 'The Health Scribe', price: 24 },
  },
  {
    id: 'life-line-reading',
    requiresImage: { type: 'palm' },
    name: 'What Your Palm Reveals About Your Vitality',
    tagline: 'A reading of your life line specifically, covering vitality and physical constitution',
    emoji: '🖐️',
    price: 49,
    domain: 'oracle-temple',
    hook: 'Your palm holds real signs of your natural energy. This reading checks them, and shows what genuinely supports your vitality.',
    whatYouGet: [
      'What your palm specifically shows about your natural energy and stamina',
      'The periods of life where this line suggests your energy runs strongest',
      'What genuinely supports your energy, based on this specific reading',
      'Any notable marks along the line, and what they traditionally mean',
      'How this reading compares to how you already feel about your own energy',
      'One real practice this month to support your vitality, not fight it',
      'Whether this line shows a consistent pattern, or notable shifts at different life stages',
      'What genuinely drains this specific kind of energy fastest, so it can be avoided',
    ],
    upsell: { id: 'dual-hand-comparison', name: "Who You Were Born As vs. Who You're Becoming", price: 69 },
  },
  {
    id: 'heart-line-love-map',
    requiresImage: { type: 'palm' },
    name: 'What Your Palm Reveals About How You Love',
    tagline: 'Your capacity for love, confirmed across two independent physical markers',
    emoji: '💗',
    price: 54,
    domain: 'oracle-temple',
    rating: 4.7,
    reviewCount: 876,
    hook: 'Two real marks in your palm are traditionally checked for how you love. Reading both together confirms the pattern, not just one.',
    whatYouGet: [
      'What one mark in your palm shows about your capacity for love',
      'What a second mark confirms or complicates about that same reading',
      'Where the two marks agree, which is where the real signal is',
      'Where they differ, and what that difference suggests',
      'The real pattern in how you tend to give love',
      'What genuinely deepens this capacity, and what has been draining it',
      'One real practice this month that helps you love more fully',
      'Whether this capacity has felt consistent across your relationships, or shifts by partner',
      'The specific kind of connection most likely to bring out the strongest version of this capacity',
    ],
    upsell: { id: 'dual-hand-comparison', name: "Who You Were Born As vs. Who You're Becoming", price: 69 },
  },
  {
    id: 'head-line-mind-map',
    requiresImage: { type: 'palm' },
    name: 'What Your Palm Reveals About How You Think',
    tagline: 'A reading of your head line, covering how you think and process',
    emoji: '🧠',
    price: 49,
    domain: 'oracle-temple',
    hook: 'Your palm holds real signs of how you think and decide. This reading checks them, and shows where this style helps or hurts.',
    whatYouGet: [
      'What your palm specifically shows about your thinking and decision style',
      'How you actually tend to reach conclusions, based on this line',
      'Where this thinking style is a real strength',
      'Where it is more likely to work against you, especially under pressure',
      'How this style compares to how you already assumed you think',
      'One real way to work with this style instead of fighting it',
      'The specific kind of problem this thinking style solves fastest',
      'What tends to happen to this style under real time pressure or stress',
    ],
    upsell: { id: 'dual-hand-comparison', name: "Who You Were Born As vs. Who You're Becoming", price: 69 },
  },
  {
    id: 'fate-line-mission-reading',
    requiresImage: { type: 'palm' },
    name: 'What Your Palm Reveals About Your Direction in Life',
    tagline: 'Your direction and ambition, confirmed across two independent physical markers',
    emoji: '🧭',
    price: 54,
    domain: 'oracle-temple',
    rating: 4.7,
    reviewCount: 743,
    hook: 'Two real marks in your palm are traditionally checked for direction and drive. Reading both confirms the pattern, not just one.',
    whatYouGet: [
      'What one mark in your palm shows about your life direction',
      'What a second mark confirms about your ambition and drive',
      'Where the two marks agree, which is where the real signal is',
      'Where they differ, and what that suggests about unresolved tension',
      'The real kind of direction this combined reading points toward',
      'What has likely been pulling you away from this direction',
      'One real step this month to realign with it',
      'Whether this direction has stayed consistent over the years, or shifted at a specific point',
      'The kind of environment most likely to support this direction, versus one that quietly resists it',
    ],
    upsell: { id: 'dual-hand-comparison', name: "Who You Were Born As vs. Who You're Becoming", price: 69 },
  },
  {
    id: 'marriage-line-reading',
    requiresImage: { type: 'palm' },
    name: 'What Your Palm Reveals About Lasting Partnership',
    tagline: 'A reading of your marriage line specifically, covering partnership and commitment',
    emoji: '💍',
    price: 49,
    domain: 'oracle-temple',
    hook: 'Your palm holds a specific real mark for lasting partnership, separate from how you love in general. This reading checks it directly.',
    whatYouGet: [
      'What your palm specifically shows about long-term partnership',
      'How this differs from what your other palm marks show about love in general',
      'Any notable marks, and what they traditionally suggest',
      'What this reading suggests about your pattern in commitment specifically',
      'How this compares to your own real experience of long-term partnership',
      'One real way to approach commitment from this pattern\'s strengths',
      'Whether this mark has stayed consistent, or changed following a specific relationship',
      'The kind of partner most likely to bring out this pattern\'s strongest form',
    ],
    upsell: { id: 'dual-hand-comparison', name: "Who You Were Born As vs. Who You're Becoming", price: 69 },
  },
  {
    id: 'thumb-willpower-reading',
    requiresImage: { type: 'palm' },
    name: 'The Thumb Willpower Reading',
    tagline: 'A reading of your thumb, covering willpower and follow-through',
    emoji: '👍',
    price: 49,
    domain: 'oracle-temple',
    hook: 'Your thumb holds real signs of your willpower and follow-through. This reading checks them, and shows how to use this strength.',
    whatYouGet: [
      'What your thumb\'s shape and flexibility traditionally show about willpower',
      'Your natural pattern for finishing what you start',
      'Where this strength is genuinely real',
      'Where it is more likely to weaken, and under what pressure',
      'How this compares to your own real experience of finishing things',
      'One real way to work with this pattern instead of fighting it',
      'Whether this strength has stayed constant, or grown since a specific period in your life',
      'The kind of goal most likely to actually hold your follow-through, versus one that quietly loses it',
    ],
    upsell: { id: 'dual-hand-comparison', name: "Who You Were Born As vs. Who You're Becoming", price: 69 },
  },
  {
    id: 'children-line-reading',
    name: 'What Your Palm Reveals About Children',
    tagline: 'What your palm indicates about children, timing, and family, read directly from your hand',
    emoji: '👶',
    price: 49,
    domain: 'oracle-temple',
    requiresImage: { type: 'palm' },
    hook: 'Certain real marks in your palm are traditionally checked for children and timing. This reading focuses only on those marks.',
    whatYouGet: [
      'What the marks in your palm traditionally show about children specifically',
      'The general timing window these marks are traditionally linked to',
      'How this differs from what your other palm marks show about partnership',
      'What these marks suggest about number or spacing, traditionally',
      'Any real difference in how strong or clear these marks are',
      'How to hold this reading alongside your own real choices and circumstances',
      'Whether these marks appear more consistent with earlier or later timing, traditionally',
      'What these marks are traditionally silent on, so expectations stay realistic',
    ],
    upsell: { id: 'dual-hand-comparison', name: "Who You Were Born As vs. Who You're Becoming", price: 69 },
  },
  {
    id: 'dual-hand-comparison',
    name: "Who You Were Born As vs. Who You're Becoming",
    tagline: 'Your non-dominant hand shows who you were born as. Your dominant hand shows who you\'ve become.',
    emoji: '🤲',
    price: 69,
    domain: 'oracle-temple',
    requiresImage: { type: 'palm' },
    isNew: true,
    hook: 'Your non-working hand shows who you were born as. Your working hand shows who you have become. This reading checks both.',
    whatYouGet: [
      'What your non-working hand shows about the pattern you were born with',
      'What your working hand shows about who you have actually become',
      'The real gap between the two, named clearly',
      'Where you have grown genuinely closer to your original nature over time',
      'Where life has pulled you away from it, for better or worse',
      'The single biggest difference between your two hands',
      'What that difference suggests about a choice worth reconsidering',
      'One real practice this month to close the gap, if you want to',
      'Whether the traits that differ most are ones you have actively worked on, or ones that just happened',
      'Whether the gap is generally widening or closing at this point in your life',
    ],
    upsell: { id: 'spiritual-scribe', name: 'The Spiritual Scribe', price: 24 },
  },
  {
    id: 'palm-trust-pattern-reading',
    name: 'Where Trust Tends to Break in Your Relationships',
    tagline: 'A palm-based reading of where trust has tended to break down in your relationships, and why',
    emoji: '🤝',
    price: 49,
    domain: 'oracle-temple',
    requiresImage: { type: 'palm' },
    hook: 'Certain real marks in your palm are linked to patterns around trust. This reading checks them honestly, and shows how to work with it.',
    whatYouGet: [
      'What the marks in your palm traditionally show about this pattern',
      'The kind of relationship situation most likely to trigger it',
      'Whether this pattern is more about temptation or about attracting instability',
      'How this differs from what your palm shows about love in general',
      'What actually working with this pattern looks like, not just naming it',
      'One real thing to do this month to build more stability',
      'Whether this pattern has shown up consistently, or mostly in specific kinds of relationships',
      'The kind of relationship structure most likely to genuinely support stability for you',
    ],
    upsell: { id: 'dual-hand-comparison', name: "Who You Were Born As vs. Who You're Becoming", price: 69 },
  },
  {
    id: 'annual-destiny-forecast',
    name: 'The Annual Destiny Forecast',
    tagline: 'A complete annual forecast synthesized across every relevant discipline',
    emoji: '🔮',
    price: 69,
    domain: 'oracle-temple',
    rating: 4.8,
    reviewCount: 1321,
    hook: 'A forecast built from one system only tells part of the story. This one checks several real systems, so nothing gets missed.',
    whatYouGet: [
      'Your whole year ahead, checked across several real, independent systems',
      'Where those systems agree, which is where the real signal is',
      'The single biggest window in the year ahead, confirmed from more than one system',
      'What this year is genuinely building toward, beneath the surface',
      'The stretch that calls for rest, confirmed across more than one reading',
      'Whether that stretch is still ahead, or already close',
      'The best use of the months left in this year',
      'One real action this month to make the most of the year',
      'Whether this year echoes last year\'s pattern, or marks a genuine break from it',
      'The specific relationship or commitment most likely to be tested before the year ends',
    ],
    upsell: { id: 'the-life-scribe', name: 'The Life Scribe', price: 24 },
  },
  {
    id: 'relocation-power-map',
    name: "Where You're Actually Meant to Live",
    tagline: "A reading of where you're actually built to live, based on your complete details",
    emoji: '🗺️',
    price: 59,
    domain: 'oracle-temple',
    hook: 'Where you live shapes more of your life than most people realize. This reading checks the real kind of place that fits you.',
    whatYouGet: [
      'The kind of place where your real pattern is most likely to thrive',
      'Exactly which parts of your life, love, money, career, health, or spirit, your current location is genuinely working with, and which it may be working against',
      "If you name up to two other places you're actually considering, a direct, side-by-side comparison of how each one fits your specific pattern",
      'The real qualities to look for in a place, not just one city',
      'How your relationship to home has shaped choices you did not connect to it',
      'What moving, if genuinely needed, would likely change for you',
      'What staying, and changing your relationship to your current place, could also achieve',
      'Whether now is a real window that favors a move',
      'An honest, direct answer if your current location shows no strong signal either way, not every place is dramatically for or against you',
      'The specific part of daily life, work, relationships, or rest, most likely to improve with the right place',
    ],
    upsell: { id: 'the-life-scribe', name: 'The Life Scribe', price: 24 },
  },
  {
    id: 'birthday-blueprint',
    name: 'The Day You Were Born, Decoded',
    tagline: 'A complete reading of what your exact birth date encodes, decoded in full',
    emoji: '🎂',
    price: 59,
    domain: 'oracle-temple',
    hook: 'Your exact birth date carries a real signature. This reading checks it fully, including what it means for your work.',
    whatYouGet: [
      'The complete signature carried by your exact birth date',
      'How this signature shows up in your daily pattern',
      'What it suggests about the kind of work that fits you',
      'The specific gift this signature carries that you may have underused',
      'What tends to renew you around your birthday, each year',
      'How this signature is often misread by people who do not share it',
      'One real way to live into this signature this month',
      'Whether this signature has felt more or less present at different points in your life',
      'The specific area of life, work, love, or health, this signature shows up strongest in',
    ],
    upsell: { id: 'life-path-deep-dive', name: 'Your Core Life Pattern, Fully Explained', price: 49 },
  },
  {
    id: 'decision-window',
    name: 'The Right Time to Decide',
    tagline: 'A reading built for a specific decision, showing the real window for making it well',
    emoji: '⏳',
    price: 59,
    domain: 'oracle-temple',
    isNew: true,
    hook: 'Some decisions land differently depending on the exact week they are made. This reading checks your real window for this one.',
    whatYouGet: [
      'A direct read on whether now is genuinely a good window for this decision',
      'The real window ahead, if now is not it, and what changes when it opens',
      'What is different about a well-timed version of this decision versus a rushed one',
      'The sign that the window is closing, so you do not miss it',
      'What to have in place before acting, specific to this decision',
      'The kind of pressure most likely to push you to act too early',
      'What waiting, if that is the right call, would cost versus save',
      'Whether the pressure to decide now is coming from the situation itself, or from other people',
      'What acting on the wrong timing has likely cost you before, if this pattern has repeated',
    ],
    upsell: { id: 'the-life-scribe', name: 'The Life Scribe', price: 24 },
  },
]

export const getPhysicalTimingToolsById = (id: string) => omniPhysicalTimingTools.find(t => t.id === id)
export const getPopularPhysicalTimingTools = () => omniPhysicalTimingTools.filter(t => t.isPopular)
