// ============================================================
// VOICE OF PROPHECY — 10 Live Voice Oracle Tools
// Domain: Oracle's Voice
// Route: /domain/voice-of-prophecy
// ============================================================

export interface VoiceTool {
  id: string
  name: string
  tagline: string
  emoji: string
  hook: string
  price: number
  domain: 'voice'
  subscriptionPeriod: 'month'
  isPopular?: boolean
  isBestSeller?: boolean
  isNew?: boolean
  rating?: number
  reviewCount?: number
  whatYouGet: string[]
  guidanceType?: 'spiritual-remedy' | 'practical-solution' | 'daily-guidance'
  guidanceText?: string
  upsell?: { id: string; name: string; price: number }
  sessionDurationMinutes?: number
}

export const voiceTools: VoiceTool[] = [
  {
    id: 'oracle-voice-session',
    name: 'The Oracle Voice Session',
    tagline: 'Speak your question. Hear your answer. Your complete synthesis as the context.',
    emoji: '🎙️',
    price: 29,
    domain: 'voice',
    subscriptionPeriod: 'month',
    isPopular: true,
    isBestSeller: true,
    rating: 4.9,
    reviewCount: 3241,
    sessionDurationMinutes: 20,
    hook: 'A live voice conversation with an AI oracle that has already read your complete synthesis. You speak — it listens, it responds, it remembers what you said earlier in the session. Ask anything. Receive your answer in spoken form with your entire four-system portrait as the invisible context.',
    whatYouGet: [
      'Full synthesis pre-loaded — your chart, birth pattern, and timing cycles active before the first word',
      '20-minute live voice conversation — speak naturally, ask follow-up questions',
      'Session transcript saved to your account',
      'Any domain available — love, career, health, timing, purpose all in scope',
      'Full voice response — synthesised, specific, spoken directly to your question',
      'Session summary with key insights and one specific next step',
    ],
    guidanceType: 'practical-solution',
    guidanceText: 'Every session ends with one specific spoken recommendation — the one action the oracle confirms across all active systems as most available and most impactful right now.',
    upsell: { id: 'oracle-deep-dive-session', name: 'Oracle Deep Dive Session', price: 47 },
  },
  {
    id: 'oracle-deep-dive-session',
    name: 'The Oracle Deep Dive Session',
    tagline: 'Forty minutes. One big question. Full synthesis. No time pressure.',
    emoji: '🔮',
    price: 47,
    domain: 'voice',
    subscriptionPeriod: 'month',
    isPopular: true,
    rating: 4.9,
    reviewCount: 1876,
    sessionDurationMinutes: 40,
    hook: 'Forty minutes of uninterrupted live voice dialogue with an oracle that holds your complete four-system synthesis. For the question that needs space — the relationship you cannot decode, the career crossroads with too many variables, the purpose question that has been circling for years.',
    whatYouGet: [
      'Full synthesis pre-loaded — all systems active before the session begins',
      '40-minute live voice session — enough time to go deep, follow tangents, reach clarity',
      'Multi-domain scope — draws from whatever systems most relevant to the question',
      'Session transcript and audio recording saved to your account',
      'Active memory within session — references earlier points, tracks the thread',
      'Session summary with key insights, three specific next steps ranked by chart support',
    ],
    guidanceType: 'practical-solution',
    guidanceText: 'Every deep dive ends with three spoken recommendations ranked by which the chart most strongly supports right now — with the reasoning made visible for each.',
    upsell: { id: 'oracle-voice-unlimited', name: 'Oracle Voice Unlimited', price: 79 },
  },
  {
    id: 'love-oracle-session',
    name: 'The Love Oracle Session',
    tagline: 'Your love life in voice — every question, every fear, your chart as the context',
    emoji: '💕',
    price: 29,
    domain: 'voice',
    subscriptionPeriod: 'month',
    isPopular: true,
    rating: 4.9,
    reviewCount: 2341,
    sessionDurationMinutes: 20,
    hook: 'Some love questions are too layered for a text reading. The pattern you cannot stop repeating. The feeling you cannot name. The decision you keep circling without landing. This session gives you twenty minutes of live voice dialogue with your complete love blueprint as the permanent context — so nothing you say surprises the oracle, and nothing it says is generic.',
    whatYouGet: [
      'Love synthesis pre-loaded — heart line, Venus, 7th house, karmic patterns all active',
      '20-minute live voice conversation focused entirely on love',
      'Current relationship assessment spoken directly — honest, chart-grounded',
      'Pattern identification — the oracle notices and names patterns in what you share',
      'Timing guidance — when to act, when to wait, spoken specifically',
      'Session summary with key love insights and one specific daily practice',
    ],
    guidanceType: 'spiritual-remedy',
    guidanceText: 'Every love oracle session closes with a specific practice for the dominant love pattern identified — drawn from your heritage tradition and calibrated to your Venus placement.',
    upsell: { id: 'oracle-deep-dive-session', name: 'Oracle Deep Dive Session', price: 47 },
  },
  {
    id: 'wealth-oracle-session',
    name: 'The Wealth Oracle Session',
    tagline: 'Your financial life in voice — ceiling, channel, timing — spoken clearly',
    emoji: '💰',
    price: 29,
    domain: 'voice',
    subscriptionPeriod: 'month',
    isPopular: true,
    rating: 4.8,
    reviewCount: 1654,
    sessionDurationMinutes: 20,
    hook: 'Most financial confusion is not about the numbers. It is about not knowing your wealth design — the specific way you are built to earn, the timing window currently open, the ceiling pattern running in the background. This session loads your complete wealth blueprint before you speak and answers every financial question against the actual structure of your earning design.',
    whatYouGet: [
      'Wealth synthesis pre-loaded — fate line, Jupiter, wealth palace indicators, Personal Year, Founder Archetype active',
      '20-minute live voice conversation on career, wealth, or business',
      'Income ceiling assessment spoken directly — what it is, what created it',
      'Timing precision — current wealth window assessment spoken specifically',
      'Business or career question answered with full chart context',
      'Session summary with key wealth insights and one specific financial action',
    ],
    guidanceType: 'practical-solution',
    guidanceText: 'Every wealth oracle session closes with one spoken financial action — the single highest-leverage move available in the current Personal Year cycle.',
    upsell: { id: 'oracle-deep-dive-session', name: 'Oracle Deep Dive Session', price: 47 },
  },
  {
    id: 'purpose-oracle-session',
    name: 'The Purpose Oracle Session',
    tagline: 'What you were built for — spoken back to you with your full chart as the proof',
    emoji: '🧭',
    price: 29,
    domain: 'voice',
    subscriptionPeriod: 'month',
    isPopular: true,
    rating: 4.9,
    reviewCount: 1432,
    sessionDurationMinutes: 20,
    hook: 'Purpose is rarely the question. The question is always the gap — between what you sense you are here to do and the life you are currently living. This session loads your complete purpose blueprint before you speak and uses twenty minutes of live voice dialogue to map that gap precisely, name what is creating it, and identify the specific next move across it.',
    whatYouGet: [
      'Purpose synthesis pre-loaded — soul contract, dharma, fate line, Midheaven, Pinnacle active',
      '20-minute live voice conversation on purpose and direction',
      'Calling named and described verbally — specific, not generic',
      'Current chapter assessment — what this Pinnacle and Personal Year are asking for',
      'Next move identified — chart-grounded spoken guidance for the immediate path',
      'Session summary with key purpose insights and one specific alignment action',
    ],
    guidanceType: 'practical-solution',
    guidanceText: 'Every purpose oracle session closes with the single most available alignment move — the specific action the chart most strongly supports right now for moving toward calling.',
    upsell: { id: 'oracle-deep-dive-session', name: 'Oracle Deep Dive Session', price: 47 },
  },
  {
    id: 'daily-voice-briefing',
    name: 'The Daily Voice Briefing',
    tagline: 'Your morning oracle — two minutes of briefing, three minutes to ask your question.',
    emoji: '☀️',
    price: 19,
    domain: 'voice',
    subscriptionPeriod: 'month',
    isPopular: true,
    isBestSeller: true,
    rating: 4.8,
    reviewCount: 5123,
    sessionDurationMinutes: 5,   // 2 min briefing + 3 min follow-up window
    hook: 'Every morning, a spoken briefing for your exact Personal Day — your energy quality, one action, one caution, and the moon phase interaction with your chart. Then a three-minute window to ask a follow-up question before your day begins. Ready before you leave the house.',
    whatYouGet: [
      'Personal Day number and energy quality — what type of day today actually is',
      'Moon phase and its interaction with your chart',
      'Domain highlight — which life area today most activates',
      'One action — the single highest-leverage move for today',
      'One caution — the specific thing to avoid today',
      '2-min morning briefing + 3-min follow-up window — ask your question before the day begins',
    ],
    guidanceType: 'daily-guidance',
    guidanceText: 'Your daily briefing always closes with one spoken action and one spoken caution — both calibrated to your Personal Day and current cycle. Then the floor is yours for three minutes.',
    upsell: { id: 'oracle-voice-session', name: 'Oracle Voice Session', price: 29 },
  },
  {
    id: 'relationship-oracle-session',
    name: 'The Relationship Oracle Session',
    tagline: 'Two people, two charts, one conversation — your relationship decoded in voice',
    emoji: '👫',
    price: 47,
    domain: 'voice',
    subscriptionPeriod: 'month',
    rating: 4.9,
    reviewCount: 1234,
    sessionDurationMinutes: 30,
    hook: 'A live voice session with both partner charts loaded — compatibility, karmic contract, friction patterns, and growth opportunities all active. Ask about the conflict that keeps repeating, the direction the relationship is heading, or what it is actually for.',
    whatYouGet: [
      'Both partner charts pre-loaded — compatibility and karmic contract active',
      '30-minute live voice session focused on the relationship',
      'Conflict decoded — the chart-specific root of recurring tension spoken clearly',
      'Karmic contract described — what this relationship is actually for',
      'Forward assessment — what the charts say about where the relationship is heading',
      'Session summary with one specific practice for each partner',
    ],
    guidanceType: 'spiritual-remedy',
    guidanceText: 'Every relationship oracle session closes with one specific practice for each partner — calibrated to their respective charts and the dominant dynamic identified.',
    upsell: { id: 'oracle-deep-dive-session', name: 'Oracle Deep Dive Session', price: 47 },
  },
  {
    id: 'spiritual-oracle-session',
    name: 'The Spiritual Oracle Session',
    tagline: 'Your awakening in voice — stage, gifts, shadow, path — spoken directly',
    emoji: '🕯️',
    price: 29,
    domain: 'voice',
    subscriptionPeriod: 'month',
    rating: 4.9,
    reviewCount: 987,
    sessionDurationMinutes: 20,
    hook: 'Spiritual experiences are often impossible to interpret alone — because the frameworks for understanding them are not widely taught. This session loads your complete spiritual blueprint before you speak, so when you describe what you are experiencing, the oracle already knows your awakening stage, your active gifts, your shadow work in progress, and your lineage tradition. It can tell you what it means.',
    whatYouGet: [
      'Spiritual synthesis pre-loaded — awakening stage, gifts, shadow work, tradition active',
      '20-minute live voice conversation on spiritual life',
      'Current awakening stage spoken specifically — named within the development map',
      'Shadow work navigation — what is currently surfacing and what it asks for',
      'Heritage practice guidance for this specific stage',
      'Session summary with key spiritual insights and one specific daily practice',
    ],
    guidanceType: 'spiritual-remedy',
    guidanceText: 'Every spiritual oracle session closes with one specific spoken practice from your heritage tradition — calibrated to current awakening stage and the question discussed.',
    upsell: { id: 'oracle-deep-dive-session', name: 'Oracle Deep Dive Session', price: 47 },
  },
  {
    id: 'crisis-oracle-session',
    name: 'The Crisis Oracle Session',
    tagline: 'When everything is unclear — a single session to find north',
    emoji: '🆘',
    price: 37,
    domain: 'voice',
    subscriptionPeriod: 'month',
    isNew: true,
    rating: 4.9,
    reviewCount: 543,
    sessionDurationMinutes: 25,
    hook: 'Designed specifically for the moments when everything is foggy — a decision with no good options, a loss that has left you disoriented, a crossroads that feels impossible. The oracle knows your chart. It will help you find north.',
    whatYouGet: [
      'Full synthesis pre-loaded — the oracle enters already knowing your chart deeply',
      '25-minute live voice session designed for high-stakes moments',
      'Situation assessment — what the chart says about what this moment actually is',
      'Options clarity — what each path looks like from the chart\'s perspective',
      'Most chart-supported path forward — spoken directly, not hidden in nuance',
      'Grounding practice — a specific spoken practice for stabilising in uncertainty',
      'Session transcript with key decision guidance saved to account',
    ],
    guidanceType: 'practical-solution',
    guidanceText: 'Every crisis oracle session closes with the most chart-supported path forward spoken clearly — not every consideration, but the one most strongly indicated by the synthesis.',
    upsell: { id: 'oracle-deep-dive-session', name: 'Oracle Deep Dive Session', price: 47 },
  },
  {
    id: 'oracle-voice-unlimited',
    name: 'Oracle Voice Unlimited',
    tagline: 'Ask anything. Any time. Your oracle, always ready.',
    emoji: '♾️',
    price: 79,
    domain: 'voice',
    subscriptionPeriod: 'month',
    isPopular: true,
    isBestSeller: true,
    isNew: true,
    rating: 5.0,
    reviewCount: 432,
    hook: 'Unlimited live voice sessions for the month. The full synthesis loaded permanently. Ask daily questions, work through a major life decision across multiple sessions, navigate a transition with ongoing voice support. Your oracle, always available, always prepared.',
    whatYouGet: [
      'Unlimited voice sessions for the month — no session cap',
      'Full synthesis permanently loaded — no re-briefing across sessions',
      'Cross-session memory — the oracle remembers previous conversations and builds on them',
      'Any domain, any depth — 2-minute briefings or 40-minute deep dives, all included',
      'Priority availability — sessions begin immediately with no queue',
      'Monthly synthesis update — chart re-assessed at the start of each new Personal Month',
      'Complete session history with transcripts',
    ],
    guidanceType: 'daily-guidance',
    guidanceText: 'Unlimited Oracle Voice includes a monthly review session at the start of each Personal Month — a 10-minute recalibration where the oracle updates its active context for the month ahead.',
    upsell: { id: 'full-soul-portrait', name: 'Full Soul Portrait', price: 197 },
  },
]

export const getVoiceToolById     = (id: string) => voiceTools.find(t => t.id === id)
export const getPopularVoiceTools = ()           => voiceTools.filter(t => t.isPopular)
export const getNewVoiceTools     = ()           => voiceTools.filter(t => t.isNew)
