// ============================================================
// WEALTH & CAREER — 12 Tools
// Domain: wealth
// Route: /domain/wealth-career
// Source of truth: tool_registry.py
// ============================================================

export interface WealthTool {
  id: string
  name: string
  tagline: string
  emoji: string
  hook: string
  price: number
  domain: 'wealth'
  isPopular?: boolean
  isBestSeller?: boolean
  isNew?: boolean
  isFlagship?: boolean
  rating?: number
  reviewCount?: number
  requiresImage?: { type: 'face' | 'palm' | 'both' } | null
  requiresPartner?: boolean
  whatYouGet: string[]
  guidanceType?: 'spiritual-remedy' | 'practical-solution' | 'daily-guidance'
  guidanceText?: string
  upsell?: { id: string; name: string; price: number }
  deliveryMinutes?: number
}

export const wealthTools: WealthTool[] = [
  {
    id: 'wealth-blueprint-reading',
    name: 'The Wealth Blueprint Reading',
    tagline: 'Your complete wealth design — how you are built to earn, keep and grow',
    emoji: '💰',
    price: 47,
    domain: 'wealth',
    isPopular: true,
    isBestSeller: true,
    rating: 4.9,
    reviewCount: 2341,
    deliveryMinutes: 20,
    hook: 'Most wealth advice assumes everyone earns and accumulates the same way. Your blueprint says otherwise. Your Life Path, 2nd house, Jupiter placement, and Destiny number each describe a specific wealth architecture that is unique to you. This reading maps the complete picture.',
    whatYouGet: [
      'Your wealth generation mode, the specific way you are built to earn',
      'Your natural wealth retention pattern, whether you accumulate or circulate and why',
      'Your income ceiling and where it sits in your current cycle',
      'The three wealth channels most aligned with your Life Path and Destiny',
      'Your Jupiter wealth cycle and when it next activates',
      'The one financial behaviour that is currently costing you the most',
    ],
    guidanceType: 'practical-solution',
    guidanceText: 'A wealth alignment protocol with three specific actions calibrated to your wealth generation mode, sequenced across 90 days.',
    upsell: { id: 'complete-wealth-synthesis', name: 'The Complete Wealth Synthesis', price: 97 },
  },
  {
    id: 'income-ceiling-breaker',
    name: 'The Income Ceiling Breaker',
    tagline: 'What is holding your income at the same level — found and removed',
    emoji: '💥',
    price: 57,
    domain: 'wealth',
    isPopular: true,
    isFlagship: true,
    rating: 4.9,
    reviewCount: 2897,
    deliveryMinutes: 20,
    hook: 'Income ceilings are not about skill gaps. They are about a specific belief, karmic pattern, or timing misalignment encoded in your chart. Most people spend years working harder against a ceiling they could simply remove. Your ceiling has a name and a dissolution path.',
    whatYouGet: [
      'The exact nature of your income ceiling, what created it and where it sits in your chart',
      'Whether the block is karmic, belief-based, or timing-based',
      'The specific thought pattern that enforces the ceiling',
      'The wealth channel most naturally aligned with your Life Path',
      'The Personal Year window when the ceiling dissolves most easily',
      'Three specific moves to break through, calibrated to your ceiling type',
    ],
    guidanceType: 'practical-solution',
    guidanceText: 'A ceiling dissolution protocol, a sequence of internal and practical actions calibrated to your specific ceiling type across one Personal Year cycle.',
    upsell: { id: 'complete-wealth-synthesis', name: 'The Complete Wealth Synthesis', price: 97 },
  },
  {
    id: 'calling-decoder',
    name: 'The Calling Decoder',
    tagline: 'What you were built to do — named precisely',
    emoji: '🧭',
    price: 47,
    domain: 'wealth',
    isPopular: true,
    rating: 4.9,
    reviewCount: 1876,
    deliveryMinutes: 20,
    hook: 'There is a difference between what you are good at and what you were made for. Most people spend their working lives in the gap between those two things — competent enough to stay, unfulfilled enough to know something is wrong. This reading uses four independent systems to name the specific contribution your blueprint was built to make, and the income model most aligned with it.',
    whatYouGet: [
      'Your dharmic calling in plain language, specific enough to act on',
      'The specific type of work that activates your highest expression',
      'The gap between your current work and the calling and how wide it is',
      'The income model most aligned with your calling',
      'One gift you consistently undervalue that others would pay for',
      'The timeline for transitioning toward calling work based on your current cycle',
    ],
    guidanceType: 'practical-solution',
    guidanceText: 'A calling activation guide with the specific first move from your current position toward calling work, timed to your current Personal Year.',
    upsell: { id: 'complete-purpose-synthesis', name: 'The Complete Purpose Synthesis', price: 97 },
  },
  {
    id: 'founder-type-reading',
    name: 'The Founder Type Reading',
    tagline: 'The business model you were built to run — not the one you have been copying',
    emoji: '🏗️',
    price: 47,
    domain: 'wealth',
    isPopular: true,
    rating: 4.8,
    reviewCount: 1234,
    deliveryMinutes: 20,
    hook: 'There are 8 founder archetypes. Most failed businesses are not failed ideas. They are the right person trying to build the wrong model for their archetype. This reading identifies your Founder Archetype, the natural business model, and the adjustment that changes the trajectory.',
    whatYouGet: [
      'Your Founder Archetype, Builder, Connector, Expert, Performer, Healer, Visionary, Steward, or Pioneer',
      'The business model most naturally aligned with your archetype',
      'The revenue model that works best for your Life Path and Soul Urge combination',
      'The team structure you need and the specific roles most critical for you',
      'Your natural marketing style, the approach that feels authentic rather than forced',
      'The failure pattern of your archetype and how to interrupt it',
    ],
    guidanceType: 'practical-solution',
    guidanceText: 'A business model alignment audit with the specific structural change most likely to unstick your current business based on your Founder Archetype.',
    upsell: { id: 'business-destiny-synthesis', name: 'The Business Destiny Synthesis', price: 87 },
  },
  {
    id: 'wealth-timing-forecast',
    name: 'The Wealth Timing Forecast',
    tagline: 'Your financial peak windows in the next 24 months — mapped precisely',
    emoji: '📈',
    price: 37,
    domain: 'wealth',
    isPopular: true,
    rating: 4.8,
    reviewCount: 2341,
    deliveryMinutes: 20,
    hook: 'Every person has specific years of elevated financial receptivity. These windows are calculable. Most people hit them accidentally. You can hit them intentionally, but only if you know when they are and what type of wealth move is optimal in each one.',
    whatYouGet: [
      'Three financial peak windows in the next 24 months, year and quarter specific',
      'What type of wealth move is optimal in each window',
      'Two caution periods to avoid major financial risk',
      'Your natural wealth channel from your Birthday Gift number',
      'One financial behaviour your current cycle is costing you most',
      'The specific action to take in the next 90 days to position for the next peak',
    ],
    guidanceType: 'practical-solution',
    guidanceText: 'A peak window preparation guide with specific actions that must be in place before each peak window opens, with exact timing.',
    upsell: { id: 'complete-wealth-synthesis', name: 'The Complete Wealth Synthesis', price: 97 },
  },
  {
    id: 'career-pivot-reading',
    name: 'The Career Pivot Reading',
    tagline: 'Whether to pivot, when to pivot, and exactly what to pivot toward',
    emoji: '🔄',
    price: 37,
    domain: 'wealth',
    rating: 4.7,
    reviewCount: 987,
    deliveryMinutes: 20,
    hook: 'Most career pivots fail not because the new direction was wrong but because the timing was wrong. Your chart has specific windows when a pivot will gain traction and specific windows when the same move will meet resistance. The reading maps both.',
    whatYouGet: [
      'Whether your current chart supports pivoting or consolidating right now',
      'The direction your Midheaven and Destiny number most support pivoting toward',
      'The specific window in the next 18 months when a pivot has the most momentum',
      'What must be in place before the pivot for it to succeed',
      'The risk your specific Founder Archetype is most likely to take that causes pivot failure',
      'A pivot timing framework calibrated to your Personal Year',
    ],
    guidanceType: 'practical-solution',
    guidanceText: 'A pivot decision framework with a specific go or wait assessment and the conditions that must be met before the move.',
    upsell: { id: 'calling-decoder', name: 'The Calling Decoder', price: 47 },
  },
  {
    id: 'money-wound-reading',
    name: 'The Money Wound Reading',
    tagline: 'The belief your face confirms is costing you the most money',
    emoji: '🩹',
    price: 47,
    domain: 'wealth',
    requiresImage: { type: 'face' },
    rating: 4.8,
    reviewCount: 765,
    deliveryMinutes: 20,
    hook: 'Every money block has a belief underneath it. Most people can name the symptom — the ceiling, the self-sabotage, the inexplicable resistance — but not the root. Your facial structure and your chart read that root independently from two different directions. When both point to the same belief, there is nowhere left for it to hide.',
    whatYouGet: [
      'The primary money wound active in your chart, named from your 2nd house and Saturn aspects',
      'The facial structure confirmation of the wound and where it shows physically',
      'The early experience your chart indicates created this money belief',
      'How the wound is manifesting across income, spending, and investment patterns',
      'The specific limiting belief and its direct opposite as a replacement',
      'A 30-day money wound clearing practice from your heritage tradition',
    ],
    guidanceType: 'spiritual-remedy',
    guidanceText: 'A money wound clearing protocol, 30 days, combining a specific daily practice with the heritage-calibrated clearing most effective for your wound type.',
    upsell: { id: 'income-ceiling-breaker', name: 'The Income Ceiling Breaker', price: 57 },
  },
  {
    id: 'salary-negotiation-oracle',
    name: 'The Salary Negotiation Oracle',
    tagline: 'The exact window, amount and approach your chart supports',
    emoji: '🤝',
    price: 29,
    domain: 'wealth',
    isPopular: true,
    rating: 4.7,
    reviewCount: 1543,
    deliveryMinutes: 20,
    hook: 'A salary negotiation made in the wrong Personal Month against the wrong backdrop will fail even when fully justified. The same ask made in the right window with the right framing will succeed beyond expectation. Your chart knows which is which.',
    whatYouGet: [
      'Your current Personal Year and what it says about financial advancement',
      'The optimal ask window in the next six months, month specific',
      'The negotiation style most aligned with your natural authority signature',
      'The number range your chart currently supports as justified',
      'The one framing that positions your ask most powerfully for your Midheaven',
      'How to handle the most likely objection based on your chart dynamics',
    ],
    guidanceType: 'practical-solution',
    guidanceText: 'A negotiation timing and framing guide with the specific approach most aligned with your authority signature and current cycle.',
    upsell: { id: 'wealth-timing-forecast', name: 'The Wealth Timing Forecast', price: 37 },
  },
  {
    id: 'side-hustle-blueprint',
    name: 'The Side Hustle Blueprint',
    tagline: 'The income stream your chart is most naturally designed to build',
    emoji: '⚡',
    price: 37,
    domain: 'wealth',
    isNew: true,
    rating: 4.7,
    reviewCount: 543,
    deliveryMinutes: 20,
    hook: 'The most sustainable side income is built from what comes easiest to you, which is precisely what your blueprint describes. Your natural gifts, your optimal work format, your ideal audience, and your current timing window all point to one specific type of side income that your chart most supports.',
    whatYouGet: [
      'The side income model most aligned with your Founder Archetype and Life Path',
      'The specific skill or gift your chart says others would pay for most readily',
      'The audience or client type most naturally attracted to your energy',
      'The format, product, service, or content, that suits your work style',
      'The launch window your current Personal Year most supports',
      'The three setup actions to take before any public launch',
    ],
    guidanceType: 'practical-solution',
    guidanceText: 'A side income launch sequence with the specific first three moves calibrated to your archetype and current timing.',
    upsell: { id: 'founder-type-reading', name: 'The Founder Type Reading', price: 47 },
  },
  {
    id: 'investment-timing-oracle',
    name: 'The Investment Timing Oracle',
    tagline: 'When your chart supports taking financial risk — and when it does not',
    emoji: '📊',
    price: 57,
    domain: 'wealth',
    isFlagship: true,
    rating: 4.8,
    reviewCount: 654,
    deliveryMinutes: 20,
    hook: 'The same investment made in a Personal Year 8 produces entirely different results than the same investment made in a Personal Year 7. Your chart has specific windows of financial expansion and specific windows of consolidation. Knowing which you are in changes every investment decision.',
    whatYouGet: [
      'Your current Personal Year and its specific relationship with financial risk',
      'The three-year investment timing map from all timing systems combined',
      'Whether your chart currently supports growth, preservation, or accumulation strategy',
      'The asset class or investment type most aligned with your natural wealth channel',
      'The specific red flag your chart identifies as your most common investment mistake',
      'The window in the next 24 months when your chart most supports a significant financial move',
    ],
    guidanceType: 'practical-solution',
    guidanceText: 'An investment timing framework with a go or wait assessment for any specific financial move and the optimal risk window in the next 24 months.',
    upsell: { id: 'complete-wealth-synthesis', name: 'The Complete Wealth Synthesis', price: 97 },
  },
  {
    id: 'leadership-signature',
    name: 'The Leadership Signature',
    tagline: 'The authority your face projects — and how to own it completely',
    emoji: '👑',
    price: 47,
    domain: 'wealth',
    requiresImage: { type: 'face' },
    isPopular: true,
    rating: 4.8,
    reviewCount: 876,
    deliveryMinutes: 20,
    hook: 'Authority is not earned with credentials. It is transmitted from a frequency. Most people in leadership positions are projecting a version of authority that is slightly out of alignment with their actual structure — and that misalignment is legible to everyone in the room before a single word is spoken. This reading names your natural leadership signature and shows you how to inhabit it fully.',
    whatYouGet: [
      'Your natural leadership archetype from facial structure analysis',
      'The specific facial features that project or undermine authority in your case',
      'How your leadership signature interacts with your 10th house and Life Path',
      'The domain where your natural authority is most readily recognised',
      'The one professional presentation adjustment that immediately increases perceived authority',
      'The leadership style most aligned with your specific combination of face and chart',
    ],
    guidanceType: 'practical-solution',
    guidanceText: 'A leadership positioning guide with the one professional repositioning move that makes your natural authority most visible to the people who need to recognise it.',
    upsell: { id: 'founder-type-reading', name: 'The Founder Type Reading', price: 47 },
  },
  {
    id: 'second-half-reading',
    name: 'The Second Half Reading',
    tagline: 'What your face predicts about your strongest decades ahead',
    emoji: '🌅',
    price: 37,
    domain: 'wealth',
    requiresImage: { type: 'face' },
    rating: 4.8,
    reviewCount: 432,
    deliveryMinutes: 20,
    hook: 'The second half of life is not a slower version of the first. It is a different chapter entirely, with its own specific power, its own specific demands, and its own windows of maximum potential. The oldest traditions of facial reading map specific features to specific decades — and those features are visible right now. This reading maps what they say about your strongest years ahead.',
    whatYouGet: [
      'The facial decade map of your structure, which features govern which years',
      'The facial assessment of your strongest upcoming decade',
      'How your Fourth Pinnacle aligns with or diverges from your facial prediction',
      'What to build now that your face says will still be standing in 20 years',
      'What to release from the first half that is no longer serving the second',
      'The two most important moves to make at the threshold between first and second half',
    ],
    guidanceType: 'practical-solution',
    guidanceText: 'A second half positioning guide with the two most important moves at the threshold, calibrated to your facial decade map and Fourth Pinnacle.',
    upsell: { id: 'elder-years-synthesis', name: 'The Elder Years Synthesis', price: 77 },
  },
]

export const getWealthToolById      = (id: string) => wealthTools.find(t => t.id === id)
export const getPopularWealthTools  = ()           => wealthTools.filter(t => t.isPopular)
export const getNewWealthTools      = ()           => wealthTools.filter(t => t.isNew)
export const getFlagshipWealthTools = ()           => wealthTools.filter(t => t.isFlagship)
