// ============================================================
// WEALTH & CAREER — 12 Tools
// Domain: wealth
// Route: /domain/wealth
// Same standard as Love: jargon-free at the source, whatYouGet
// depth tied honestly to price tier (see love-tools.ts header).
// ============================================================

export interface WealthTool {
  id: string
  name: string
  tagline: string
  emoji: string
  hook: string
  price: number
  domain: 'wealth'
  isPopular?: boolean
  isBestSeller?: boolean
  isNew?: boolean
  rating?: number
  reviewCount?: number
  whatYouGet: string[]
  guidanceType?: 'practical-solution' | 'daily-guidance'
  guidanceText?: string
  upsell?: { id: string; name: string; price: number }
}

export const wealthTools: WealthTool[] = [
  {
    id: 'wealth-blueprint-reading',
    name: 'The Way Money Moves Through You',
    tagline: 'The way money was always going to move through you, once you stop fighting the pattern',
    emoji: '🌊',
    price: 34,
    domain: 'wealth',
    rating: 4.8,
    reviewCount: 2103,
    hook: 'Everyone earns money in their own way. This reading shows the real pattern behind how money moves through you, whether it has shifted over the years, and one clear step to stop working against it.',
    whatYouGet: [
      'Your natural way of earning and using money, named clearly',
      'Why normal money advice has felt slightly wrong for you before',
      'The one way you are most likely to lose money without noticing',
      'The one way you are most likely to make money, once you stop fighting your own pattern',
      'Whether this pattern is deep and fixed in you, or something that can shift with the right change',
      'Whether this pattern has shifted at all over the years, or has stayed exactly the same',
      'The specific financial decision this pattern is most likely to affect first',
      'Try one simple money habit this month that actually fits how you are built',
    ],
    upsell: { id: 'wealth-scribe', name: 'The Wealth Scribe', price: 24 },
  },
  {
    id: 'income-ceiling-breaker',
    name: 'The Income Ceiling, Broken',
    tagline: "The specific, repeating reason your income keeps capping at the same number",
    emoji: '🧱',
    price: 34,
    domain: 'wealth',
    isPopular: true,
    isBestSeller: true,
    rating: 4.9,
    reviewCount: 3567,
    hook: 'You may have hit the same income level more than once, in more than one job. This reading finds the real reason behind that ceiling, and one clear step to finally break through it.',
    whatYouGet: [
      'The exact income level you keep circling back to, and why it is not random',
      'The real reason you keep hitting this ceiling, named clearly',
      'The moment in your working life when this ceiling first appeared',
      'Whether this ceiling is starting to loosen now, or still fully locked in place',
      'The kind of opportunity most likely to finally break through it',
      'Whether this ceiling has shown up in more than one job, or is tied to this one specifically',
      'The kind of environment most likely to make this ceiling harder to break',
      'Take one clear action this month that works directly against this ceiling',
    ],
    guidanceType: 'practical-solution',
    guidanceText: 'One specific move available to you in the next 90 days that directly targets the actual mechanism, not the symptom.',
    upsell: { id: 'wealth-scribe', name: 'The Wealth Scribe', price: 24 },
  },
  {
    id: 'calling-decoder',
    name: 'The Work You Were Built to Do',
    tagline: 'The work you were actually built for, not the version a career quiz gives you',
    emoji: '🧭',
    price: 34,
    domain: 'wealth',
    rating: 4.7,
    reviewCount: 1842,
    hook: 'Most career advice starts with what jobs exist, not who you are. This reading shows the work you are actually built for, whether it emerged early or later in life, and one first step to take.',
    whatYouGet: [
      'The kind of work you are genuinely built for, not just the closest job available',
      'Why you have likely been talked out of this path before, and by whom',
      'The type of workplace where this kind of work grows, and the type where it dies',
      'Whether this calling is a strong, fixed part of you, or something still forming',
      'The real difference between your current job and the work that would actually fit',
      'Whether this calling has shown up consistently since childhood, or emerged later in life',
      'The kind of income this calling is realistically capable of producing, stated honestly',
      'Take one small step this month toward this kind of work',
    ],
    upsell: { id: 'wealth-scribe', name: 'The Wealth Scribe', price: 24 },
  },
  {
    id: 'money-wound-reading',
    name: "The Belief That's Costing You Money",
    tagline: 'The exact belief about money that has been running your decisions without your permission',
    emoji: '🩹',
    price: 34,
    domain: 'wealth',
    hook: 'One old belief about money may be quietly running your decisions, sometimes traced to a single event, sometimes just absorbed over time. This reading names it clearly and shows you how to change it.',
    whatYouGet: [
      'The specific belief about money that has been running your decisions without you knowing',
      'Where this belief most likely came from',
      'Three normal decisions where this belief has quietly shown up',
      'What this belief has likely cost you in real terms, not just in feeling',
      'Whether this belief is deeply set in you, or can shift quickly once you see it clearly',
      'Whether this belief came from a specific event, or was simply absorbed over time',
      'The one financial goal this belief has most likely kept just out of reach',
      'Start replacing this belief with a better one, beginning with something small this week',
    ],
    upsell: { id: 'wealth-scribe', name: 'The Wealth Scribe', price: 24 },
  },
  {
    id: 'salary-negotiation-oracle',
    name: 'Ask for More Money',
    tagline: 'The best window to ask, and how to time the ask itself',
    emoji: '💬',
    price: 29,
    domain: 'wealth',
    isBestSeller: true,
    rating: 4.8,
    reviewCount: 2988,
    hook: 'Timing changes how a money conversation goes, more than most people realize. This reading finds your best window to ask for more, checks whether it is tied to this role, and shows how to use it.',
    whatYouGet: [
      'Your best window ahead for asking for more money',
      'Whether that window is still fully open or already starting to close',
      'The best way to ask, based on your natural style',
      'The one mistake most likely to work against you if you ask too soon',
      'What to do if the answer is no',
      'Whether this window is tied to your current role specifically, or would apply anywhere you worked',
      'What asking for less than you are worth has likely already cost you',
      'Prepare for the ask this week with something specific to say or do',
    ],
    upsell: { id: 'wealth-scribe', name: 'The Wealth Scribe', price: 24 },
  },
  {
    id: 'wealth-timing-forecast',
    name: 'Your Next 24 Months of Money',
    tagline: 'Your finances, mapped two years ahead',
    emoji: '📊',
    price: 29,
    domain: 'wealth',
    hook: 'Two years is enough time to see real change in your money life, and short enough to plan around. This reading maps it out, checks if old patterns are repeating, and shows what to do now.',
    whatYouGet: [
      'The shape of your money life, month by month, for the next two years',
      'Your strongest window in this time for a smart financial move',
      'The stretch where saving carefully, not risking, is the right move',
      'The single biggest turning point in your money life over the next two years',
      'Whether you are heading into that turning point, or just past it',
      'Whether the pattern of the last two years is repeating, or genuinely shifting',
      'The specific area, saving, earning, or investing, this period favors most',
      'Prepare for your strongest window by starting something specific this month',
    ],
    upsell: { id: 'wealth-scribe', name: 'The Wealth Scribe', price: 24 },
  },
  {
    id: 'side-hustle-blueprint',
    name: 'The Income Stream Waiting to Be Built',
    tagline: 'The specific income stream built for your actual strengths',
    emoji: '🌱',
    price: 29,
    domain: 'wealth',
    hook: 'Most side hustle advice is the same for everyone, regardless of who they actually are. This reading shows the one that actually fits your specific strengths, and exactly how to start it.',
    whatYouGet: [
      'The type of extra income stream that actually fits your natural strengths',
      'Why the popular option everyone else is trying may not work as well for you',
      'The first real problem this type of income stream is likely to hit',
      'Whether this is a fast, natural fit for you, or something to build slowly',
      'What would help this idea survive its first hard month',
      'Whether this income stream can realistically run alongside your current job, or needs your full attention',
      'The specific skill you already have that this idea depends on most',
      'Start it this week with one small, real first step',
    ],
    upsell: { id: 'wealth-scribe', name: 'The Wealth Scribe', price: 24 },
  },
  {
    id: 'investment-timing-oracle',
    name: 'When to Take the Financial Risk',
    tagline: "The real window for a financial risk, not general encouragement to take one",
    emoji: '🎲',
    price: 29,
    domain: 'wealth',
    hook: 'A good decision and a well-timed decision are not always the same thing, even when the reasoning is sound. This reading finds your real window for taking a financial risk, and what waiting would cost.',
    whatYouGet: [
      'Your real window ahead for a financial risk that is likely to pay off',
      'Whether that window is opening now or already starting to close',
      'The kind of risk that fits your pattern, and the kind that usually backfires for you',
      'What to have in place before taking this risk',
      'The warning sign that this window is closing',
      'Whether this risk is more about money, time, or reputation, and which one matters most here',
      'What waiting past this window would most likely cost you',
      'Check or prepare one thing this week before you act',
    ],
    upsell: { id: 'wealth-scribe', name: 'The Wealth Scribe', price: 24 },
  },
  {
    id: 'career-pivot-reading',
    name: 'Should You Pivot Careers',
    tagline: 'A direct read on whether now is the moment to change direction',
    emoji: '🔀',
    price: 44,
    domain: 'wealth',
    isPopular: true,
    rating: 4.8,
    reviewCount: 1654,
    hook: 'Career changes often fail from bad timing, not bad ideas. This reading gives you a clear answer on whether now is the right time, and the direction most likely to actually hold your interest.',
    whatYouGet: [
      'A clear answer on whether your unhappiness is about this job, or something bigger',
      'Whether now is genuinely the right window for a change, or whether waiting serves you better',
      'The real direction this change should take, not just a list of options',
      'What you would be leaving behind that is actually worth grieving, not just guilt',
      'The fear most likely to stop you from making this change',
      'Whether you are moving through a major life-stage shift right now, which makes this change more likely to succeed',
      'The specific type of role most likely to actually hold your interest long term',
      'Take one clear first step this month if the answer is yes',
    ],
    guidanceType: 'practical-solution',
    guidanceText: 'If the read is yes, the single first move to make before telling anyone else about the decision.',
    upsell: { id: 'wealth-scribe', name: 'The Wealth Scribe', price: 24 },
  },
  {
    id: 'leadership-signature',
    name: 'Your Leadership Signature',
    tagline: 'How authority and leadership actually move through you, and where it is being held back',
    emoji: '👑',
    price: 44,
    domain: 'wealth',
    rating: 4.7,
    reviewCount: 1209,
    hook: 'Some people command a room without trying, while others carry real authority that never quite lands. This reading names your real leadership pattern, where it is strong, and one way to use it better.',
    whatYouGet: [
      'Your specific leadership pattern, named clearly',
      'Where this leadership is already genuinely strong, even if no one has told you',
      'The one habit most likely quietly working against how people see you',
      'The type of room where your leadership works best',
      'The type of room where it currently falls flat, and why',
      'Whether this pattern shows up the same way at work and at home, or shifts by setting',
      'The kind of team or organization most likely to actually need what you offer',
      'Make one change this month that would let your leadership fully show',
    ],
    upsell: { id: 'wealth-scribe', name: 'The Wealth Scribe', price: 24 },
  },
  {
    id: 'founder-type-reading',
    name: 'The Business Shaped Like You',
    tagline: 'The specific kind of business built for your actual nature, not a one-size-fits-all quiz',
    emoji: '🏛️',
    price: 49,
    domain: 'wealth',
    isBestSeller: true,
    rating: 4.9,
    reviewCount: 1988,
    hook: 'Not everyone is built for the same kind of business, and starting the wrong shape can cost real years. This reading shows the shape of business that actually fits you, and whether now is realistic.',
    whatYouGet: [
      'The size and shape of business that actually fits your nature',
      'The role you are best suited for inside that business, founder, operator, or something else',
      'The kind of business partner who would complement you, if you need one',
      'The most common mistake people like you make in the first two years',
      'Whether now is a strong stage in your life to start, or whether waiting would serve you better',
      'Whether this business shape is realistic given your current resources, or something to grow into',
      'The single biggest risk to starting before you are genuinely ready',
      'Take one first step this month if you decide to start',
    ],
    upsell: { id: 'business-destiny-synthesis', name: 'Your Business, Fully Mapped', price: 79 },
  },
  {
    id: 'second-half-reading',
    name: 'Your Strongest Career Decades Ahead',
    tagline: 'Mapping the second half of your working life, where your strongest years are still ahead',
    emoji: '🌅',
    price: 49,
    domain: 'wealth',
    rating: 4.8,
    reviewCount: 976,
    hook: 'Many people believe their best working years happen early, and spend later decades coasting because of it. This reading shows you which pattern is actually yours, and whether it has already begun.',
    whatYouGet: [
      'Whether your pattern points to an early career peak, or a later one',
      'What you should let go of now to make room for what is coming',
      'The decade ahead most likely to bring your highest income and authority',
      'What kind of work will satisfy you most at this stage, compared to before',
      'The most common mistake people at your stage make',
      'Whether this pattern has already started to show up, or is still further ahead',
      'What preparing too early or too late would each likely cost you',
      'Start doing one thing this month to prepare for your strongest decade',
    ],
    upsell: { id: 'wealth-scribe', name: 'The Wealth Scribe', price: 24 },
  },
]

export const getWealthToolById = (id: string) => wealthTools.find(t => t.id === id)
export const getPopularWealthTools = () => wealthTools.filter(t => t.isPopular)
