// ============================================================
// WELLNESS & SPIRITUALITY — 12 Tools
// Domain: wellness
// Route: /domain/wellness-spirituality
// Source of truth: tool_registry.py
// ============================================================

export interface WellnessTool {
  id: string
  name: string
  tagline: string
  emoji: string
  hook: string
  price: number
  domain: 'wellness'
  isPopular?: boolean
  isBestSeller?: boolean
  isNew?: boolean
  isFlagship?: boolean
  rating?: number
  reviewCount?: number
  requiresImage?: { type: 'face' | 'palm' | 'both' } | null
  requiresPartner?: boolean
  whatYouGet: string[]
  guidanceType?: 'spiritual-remedy' | 'practical-solution' | 'daily-guidance'
  guidanceText?: string
  upsell?: { id: string; name: string; price: number }
  deliveryMinutes?: number
}

export const wellnessTools: WellnessTool[] = [
  {
    id: 'body-constitution-reading',
    name: 'The Body Constitution Reading',
    tagline: 'Your body\'s actual design — and why generic health advice keeps failing you',
    emoji: '⚕️',
    price: 37,
    domain: 'wellness',
    isPopular: true,
    rating: 4.9,
    reviewCount: 1876,
    deliveryMinutes: 20,
    hook: 'You are not failing at health. Generic health advice is failing your specific constitution. No two people have the same body type, the same energy system, or the same relationship with food, movement, and rest. Four independent traditions of constitutional medicine each developed a framework for reading your specific type — and when all four agree, the picture they create is the most accurate health portrait available.',
    whatYouGet: [
      'Your constitutional body type with full diet and lifestyle implications across all four traditions',
      'Your elemental type with specific foods, directions, and seasons that balance your system',
      'Your chart-based health profile from your 6th house and planetary health indicators',
      'What your body needs that it is not currently getting across physical, nutritional, and energetic dimensions',
      'What makes your body thrive, specific foods, movement types, environments, and relationship conditions',
      'A 30-day constitutional reset protocol calibrated to your dominant constitution type',
    ],
    guidanceType: 'practical-solution',
    guidanceText: 'A 30-day constitutional reset protocol with specific dietary, movement, and sleep adjustments calibrated to your dominant constitution type.',
    upsell: { id: 'complete-health-synthesis', name: 'The Complete Health Synthesis', price: 97 },
  },
  {
    id: 'shadow-work-reading',
    name: 'The Shadow Work Reading',
    tagline: 'What you hide from yourself — and why it is your greatest power',
    emoji: '🌑',
    price: 47,
    domain: 'wellness',
    isPopular: true,
    rating: 4.9,
    reviewCount: 1654,
    deliveryMinutes: 20,
    hook: 'Your shadow is not your darkness. It is your disowned power. Every quality you suppress takes energy to manage. That suppression runs quietly in the background of everything you do, showing up as inexplicable reactions, patterns outside your control, and a persistent sense that something is being held back. This reading names what lives in your shadow and maps the integration path.',
    whatYouGet: [
      'Your primary shadow complex, the main suppressed quality named from your 12th house, Pluto, and birth pattern',
      'How the shadow currently shows up through projection, compulsive behaviours, or disproportionate reactions',
      'What the shadow is protecting, because shadows always protect something specific',
      'The gold in the shadow, the disowned strength that becomes available when integrated',
      'A 60-day shadow integration practice from your ancestral tradition structured in three phases',
      'What changes after integration across relationships, creative output, and professional presence',
    ],
    guidanceType: 'spiritual-remedy',
    guidanceText: 'A 60-day shadow integration practice from your ancestral tradition, structured in three phases: recognition, encounter, and integration.',
    upsell: { id: 'shadow-and-light-synthesis', name: 'The Shadow and Light Synthesis', price: 87 },
  },
  {
    id: 'ancestral-wound-reading',
    name: 'The Ancestral Wound Reading',
    tagline: 'The pattern you inherited — and how to be the one who ends it',
    emoji: '🌳',
    price: 57,
    domain: 'wellness',
    isFlagship: true,
    rating: 4.8,
    reviewCount: 876,
    deliveryMinutes: 20,
    hook: 'Some of what you carry is not yours. It arrived before you were born, transmitted through your lineage as a recurring pattern that has expressed across generations in different forms but the same essential structure. This reading names what you are carrying, how far back it goes, and identifies your role in whether it continues.',
    whatYouGet: [
      'The dominant ancestral pattern confirmed across your 4th house, Moon, Saturn, and south node indicators',
      'How far back it goes and why the depth matters for how you work with it',
      'How this ancestral pattern is currently active in your present circumstances',
      'Whether you are carrying the pattern, being asked to transform it, or positioned as the one who stops it',
      'What healing this pattern looks like in practice for your specific chart',
      'A heritage-calibrated ancestral healing practice for the pattern identified, structured as a 40-day commitment',
    ],
    guidanceType: 'spiritual-remedy',
    guidanceText: 'A heritage-calibrated ancestral healing practice, a specific ritual, prayer, or practice from your lineage tradition for the pattern identified, structured as a 40-day commitment with clear completion markers.',
    upsell: { id: 'complete-spiritual-synthesis', name: 'The Complete Spiritual Synthesis', price: 97 },
  },
  {
    id: 'spiritual-gifts-reading',
    name: 'The Spiritual Gifts Reading',
    tagline: 'The specific spiritual capacities you arrived with — and how to develop them',
    emoji: '✨',
    price: 47,
    domain: 'wellness',
    requiresImage: { type: 'palm' },
    isPopular: true,
    rating: 4.9,
    reviewCount: 1234,
    deliveryMinutes: 20,
    hook: 'Spiritual gifts are not evenly distributed and they are not invented. They are specific perceptual and relational capacities encoded in your blueprint — readable from your sky map, your birth pattern, and your physical markers simultaneously. This reading names what is already active in you and what is dormant, waiting for permission to develop.',
    whatYouGet: [
      'Your primary active gift, clairvoyance, clairsentience, healing, prophecy, teaching, or channelling, defined plainly',
      'Your secondary gifts and what activates them',
      'The current state of your gift, whether dormant, emerging, active, or suppressed, and what created that state',
      'What your gift is for, the specific type of service it is designed to make',
      'The specific practice, training, or discipline most aligned with developing your primary gift responsibly',
      'The specific energetic grounding and discernment practices your gift type requires',
    ],
    guidanceType: 'spiritual-remedy',
    guidanceText: 'A gift activation and protection practice from your tradition, a specific daily discipline for developing your primary gift responsibly with the protection practices appropriate for your gift type.',
    upsell: { id: 'complete-spiritual-synthesis', name: 'The Complete Spiritual Synthesis', price: 97 },
  },
  {
    id: 'past-life-reading',
    name: 'The Past Life Reading',
    tagline: 'What you carried in from before — and how it is shaping this lifetime',
    emoji: '🔮',
    price: 57,
    domain: 'wellness',
    requiresImage: { type: 'palm' },
    isFlagship: true,
    rating: 4.8,
    reviewCount: 765,
    deliveryMinutes: 20,
    hook: 'Most people sense that certain patterns in their life run deeper than this lifetime can explain. The attraction that felt like recognition. The fear with no origin. The talent that arrived fully formed. Your blueprint encodes the soul\'s history with remarkable specificity — and this reading decodes it across multiple independent systems to show you what you actually carried in.',
    whatYouGet: [
      'The past life theme most active in your current chart from south node and sky map indicators combined',
      'The gifts and capacities you carried in from previous incarnations',
      'The unresolved patterns that crossed the threshold with you',
      'How past life contracts are manifesting in your current relationships and circumstances',
      'The specific lesson this lifetime is asking you to demonstrate that previous lifetimes could not complete',
      'A clearing practice for the past life pattern most actively affecting your present',
    ],
    guidanceType: 'spiritual-remedy',
    guidanceText: 'A past life pattern clearing practice from your heritage tradition, calibrated to the specific unresolved contract identified as most active.',
    upsell: { id: 'relationship-karma-synthesis', name: 'The Relationship Karma Synthesis', price: 87 },
  },
  {
    id: 'chakra-blueprint',
    name: 'The Chakra Blueprint Reading',
    tagline: 'Which energy centres are blocked, which are overactive, and the specific remedy',
    emoji: '🌀',
    price: 37,
    domain: 'wellness',
    isPopular: true,
    rating: 4.8,
    reviewCount: 1432,
    deliveryMinutes: 20,
    hook: 'Your chart describes the state of your energy system with a specificity that general chakra content cannot match. Your planetary placements, elemental distribution, and current timing cycle all correspond to specific chakra states. This reading maps your current energy architecture and the targeted remedy for each imbalance.',
    whatYouGet: [
      'Your primary blocked chakra from your chart\'s planetary and elemental signatures',
      'Your primary overactive chakra and what is driving the excess',
      'How the blocked and overactive states interact and reinforce each other',
      'The specific life domain most affected by each imbalance',
      'A targeted practice for each imbalanced energy centre from your heritage tradition',
      'The natural remedy, colour, sound, or practice, most effective for your constitutional type',
    ],
    guidanceType: 'spiritual-remedy',
    guidanceText: 'A chakra rebalancing protocol with specific daily practices for each imbalanced centre, calibrated to your constitutional type and current timing.',
    upsell: { id: 'body-constitution-reading', name: 'The Body Constitution Reading', price: 37 },
  },
  {
    id: 'dark-night-navigator',
    name: 'The Dark Night Navigator',
    tagline: 'A map for the most difficult spiritual experience — so you know you are not lost',
    emoji: '🕯️',
    price: 47,
    domain: 'wellness',
    isNew: true,
    rating: 4.9,
    reviewCount: 654,
    deliveryMinutes: 20,
    hook: 'The dark night of the soul is one of the most disorienting experiences available to a human being and one of the most significant. It is also one of the most misidentified. Not all suffering is a dark night, and misidentifying it leads to the wrong response. This reading confirms whether you are in a dark night, maps your position within it, and shows you what helps and what hinders.',
    whatYouGet: [
      'Whether you are in a dark night, a direct confirmation or ruling out from chart indicators',
      'What phase of the dark night you are in, dissolution, emptiness, searching, glimpsing, or integration',
      'What triggered this dark night from your chart and personal cycle conditions',
      'What is being dismantled and why this specific structure needed to come down',
      'What is waiting on the other side, the specific quality of being available after this dissolution',
      'What helps and what hinders, specific practices and conditions for your particular dark night',
    ],
    guidanceType: 'spiritual-remedy',
    guidanceText: 'A dark night navigation practice drawn from the mystical tradition most aligned with your chart\'s spiritual lineage, not to end the dark night prematurely but to move through it with integrity.',
    upsell: { id: 'shadow-work-reading', name: 'The Shadow Work Reading', price: 47 },
  },
  {
    id: 'intuition-activation',
    name: 'The Intuition Activation Reading',
    tagline: 'What form your intuition takes — and how to stop doubting it',
    emoji: '👁️',
    price: 37,
    domain: 'wellness',
    rating: 4.7,
    reviewCount: 987,
    deliveryMinutes: 20,
    hook: 'Everyone is intuitive. Not everyone is intuitive in the same way. Clairsentience, claircognisance, clairvoyance, and prophetic dreaming are all different faculties with different development paths. Your chart names which faculty is your primary channel and why you have been doubting the very signal you should be trusting.',
    whatYouGet: [
      'Your primary intuitive faculty from your chart\'s Moon, Neptune, and 12th house configuration',
      'The specific form your intuition most commonly takes, feelings, knowing, images, or dreams',
      'Why you have been dismissing or second-guessing your primary intuitive signal',
      'The conditions under which your intuition is most reliable versus most distorted',
      'A daily practice for developing and trusting your specific intuitive channel',
      'How to distinguish intuition from fear in your specific chart configuration',
    ],
    guidanceType: 'spiritual-remedy',
    guidanceText: 'An intuition development practice calibrated to your specific faculty type, with daily exercises for building reliability and a discernment framework for your chart.',
    upsell: { id: 'spiritual-gifts-reading', name: 'The Spiritual Gifts Reading', price: 47 },
  },
  {
    id: 'vitality-code',
    name: 'The Vitality Code',
    tagline: 'Why your energy is where it is — and the specific path to your natural peak',
    emoji: '⚡',
    price: 47,
    domain: 'wellness',
    requiresImage: { type: 'palm' },
    rating: 4.8,
    reviewCount: 2103,
    deliveryMinutes: 20,
    hook: 'Your energy level is not a willpower problem. It is a constitutional code that most people never crack. Your physical blueprint, your Sun and Mars placement, your body type, and your current personal cycle together reveal a specific vitality code: why your energy is exactly where it is, the specific drains responsible, and the precise path to your constitutional peak.',
    whatYouGet: [
      'Your natural vitality ceiling, the constitutional energy available when fully aligned with your design',
      'What is currently depleting you across physical, energetic, emotional, and circumstantial dimensions',
      'Your natural energy rhythm, the daily, weekly, and seasonal rhythms that match your constitutional design',
      'The foods that power your constitution and the movement that restores rather than depletes',
      'Your hand vitality reading, what your physical markers reveal about your life force trajectory',
      'A 14-day vitality recovery protocol targeting your specific primary vitality drain',
    ],
    guidanceType: 'practical-solution',
    guidanceText: 'A personalised vitality recovery protocol, a 14-day sequence of constitutional adjustments targeting your specific primary vitality drain, with daily actions and measurable check-ins.',
    upsell: { id: 'body-constitution-reading', name: 'The Body Constitution Reading', price: 37 },
  },
  {
    id: 'abundance-frequency-audit',
    name: 'The Abundance Frequency Audit',
    tagline: 'What your face reveals about your current relationship with abundance',
    emoji: '💫',
    price: 37,
    domain: 'wellness',
    requiresImage: { type: 'face' },
    rating: 4.7,
    reviewCount: 765,
    deliveryMinutes: 20,
    hook: 'Abundance is a frequency before it is a circumstance. Most people trying to change their financial reality are working at the level of action while the actual block is at the level of signal. Your facial structure and your personal cycle read that signal independently from two different directions. This reading names the specific broadcast you are currently running — and the precise adjustment that shifts it.',
    whatYouGet: [
      'Your current abundance frequency from the facial structure reading of your expression and features',
      'The specific feature or expression habit that most suppresses your abundance signal',
      'The personal cycle abundance indicator most active in your current phase',
      'Whether your chart is currently in an abundance-attracting or abundance-conserving phase',
      'The one specific shift, internal or physical, that most immediately raises your abundance frequency',
      'A 21-day abundance frequency practice from your heritage tradition',
    ],
    guidanceType: 'practical-solution',
    guidanceText: 'A 21-day abundance frequency practice combining a daily internal practice with the specific physical adjustment that most shifts your facial abundance signal.',
    upsell: { id: 'body-constitution-reading', name: 'The Body Constitution Reading', price: 37 },
  },
  {
    id: 'sleep-and-dreams-reading',
    name: 'The Sleep and Dreams Reading',
    tagline: 'What your chart says about your sleep patterns and what your dreams are telling you',
    emoji: '🌙',
    price: 29,
    domain: 'wellness',
    isPopular: true,
    rating: 4.7,
    reviewCount: 1234,
    deliveryMinutes: 20,
    hook: 'Your Moon sign describes your sleep architecture. Your Neptune placement describes your dream faculty. Your 12th house describes your relationship with the unconscious. These three together create a specific sleep and dream profile that explains why you sleep the way you do and what your dream life is trying to communicate.',
    whatYouGet: [
      'Your sleep architecture from your Moon sign, what you need to sleep well and what disrupts you',
      'Your dream faculty from your Neptune placement and 12th house, what your dreams are for',
      'The recurring dream theme your chart predicts and what it is processing',
      'The sleep environment and pre-sleep practice most calibrated to your Moon sign',
      'What your chart says about the specific time of night most important for your restorative sleep',
      'A moon-aligned sleep practice from your heritage tradition',
    ],
    guidanceType: 'practical-solution',
    guidanceText: 'A Moon-aligned sleep protocol with specific pre-sleep practices and environmental adjustments calibrated to your Moon sign and 12th house configuration.',
    upsell: { id: 'chakra-blueprint', name: 'The Chakra Blueprint Reading', price: 37 },
  },
  {
    id: 'purpose-activation-reading',
    name: 'The Purpose Activation Reading',
    tagline: 'Not just what your purpose is — but how to actually live it starting now',
    emoji: '🎯',
    price: 47,
    domain: 'wellness',
    requiresImage: { type: 'palm' },
    rating: 4.9,
    reviewCount: 1234,
    deliveryMinutes: 20,
    hook: 'Knowing your purpose is not the problem. Most people have a sense of it. The problem is the gap between knowing and living. That gap has a specific structure visible in your chart: the blocks creating it, the conditions under which it closes, and the precise first step from purpose-knowing to purpose-living.',
    whatYouGet: [
      'Your purpose stated clearly, not a vague aspiration but a specific vocational and spiritual function',
      'Why you have not been living it fully, the specific blocks creating the gap named without judgment',
      'The activation point, the specific inner and outer conditions that mark the activation of your purpose',
      'Whether you are already in your activation window and what it means for your next move',
      'The single most important action available right now that moves from purpose-knowing to purpose-living',
      'Your fate line reading from your physical blueprint, when and how your purpose activates in physical reality',
    ],
    guidanceType: 'practical-solution',
    guidanceText: 'A purpose activation sequence, the specific first move, the timing for it, and the three conditions your chart says must be in place before you take it.',
    upsell: { id: 'complete-purpose-synthesis', name: 'The Complete Purpose Synthesis', price: 97 },
  },
]

export const getWellnessToolById      = (id: string) => wellnessTools.find(t => t.id === id)
export const getPopularWellnessTools  = ()           => wellnessTools.filter(t => t.isPopular)
export const getNewWellnessTools      = ()           => wellnessTools.filter(t => t.isNew)
export const getFlagshipWellnessTools = ()           => wellnessTools.filter(t => t.isFlagship)
