// ============================================================
// WELLNESS & SPIRITUALITY — 14 Tools
// Domain: wellness
// Route: /domain/wellness
// Same standard as Love and Wealth: jargon-free at the source
// (no "chakra" as a literal word even where the concept is energy
// centers — "energy center" carries the same meaning cleanly),
// whatYouGet depth tied honestly to price tier.
// ============================================================

export interface WellnessTool {
  id: string
  name: string
  tagline: string
  emoji: string
  hook: string
  price: number
  domain: 'wellness'
  isPopular?: boolean
  isBestSeller?: boolean
  isNew?: boolean
  rating?: number
  reviewCount?: number
  whatYouGet: string[]
  guidanceType?: 'practical-solution' | 'daily-guidance'
  guidanceText?: string
  upsell?: { id: string; name: string; price: number }
}

export const wellnessTools: WellnessTool[] = [
  {
    id: 'body-constitution-reading',
    name: 'Your Body, Built Different, Not Broken',
    tagline: 'Why generic health advice was never going to work for your particular body',
    emoji: '🌿',
    price: 34,
    domain: 'wellness',
    rating: 4.8,
    reviewCount: 1876,
    hook: 'You are not failing at health. Your body was never built like everyone else. This reading shows your real body type, whether it has always felt this way, and one change that actually fits you.',
    whatYouGet: [
      'Your real body type, named clearly, not a generic health category',
      'What genuinely helps your specific body, even when it goes against popular advice',
      'What quietly works against you, even when people call it healthy',
      'The one area of your body most likely to show stress first, before anything else does',
      'What real rest looks like for your specific body',
      'Whether your pattern points to a specific vulnerability worth watching, not just a general type',
      'Whether this body type has felt this way your whole life, or shifted at some point',
      'Make one small change this week that actually fits your body type',
    ],
    upsell: { id: 'health-scribe', name: 'The Health Scribe', price: 24 },
  },
  {
    id: 'shadow-work-reading',
    name: "The Parts of Yourself You've Been Avoiding",
    tagline: 'The specific pattern you keep circling in shadow work, named clearly',
    emoji: '🌑',
    price: 44,
    domain: 'wellness',
    isPopular: true,
    isBestSeller: true,
    rating: 4.9,
    reviewCount: 2745,
    hook: 'There is a pattern in you that you keep almost seeing, then looking away from. This reading names it clearly, checks whether it has gotten louder recently, and gives you one way to face it.',
    whatYouGet: [
      'The specific pattern you have been circling without fully naming it',
      'Why this pattern has stayed just out of reach until now',
      'The situation most likely to bring this pattern into the open',
      'The story you tell yourself to avoid looking at it directly',
      'Whether this pattern is deeply set in you, or easier to shift than you think',
      'Whether this pattern has gotten louder recently, or has been quiet for a while',
      'What this pattern has quietly been costing you, even in the periods it stays hidden',
      'Sit with one honest question this week that starts facing it directly',
    ],
    guidanceType: 'practical-solution',
    guidanceText: 'One specific situation in the coming weeks where this pattern is likely to surface, and what to do differently when it does.',
    upsell: { id: 'spiritual-scribe', name: 'The Spiritual Scribe', price: 24 },
  },
  {
    id: 'ancestral-wound-reading',
    name: 'The Family Pattern You Inherited',
    tagline: 'The inherited family pattern still quietly shaping your life',
    emoji: '🌳',
    price: 44,
    domain: 'wellness',
    rating: 4.8,
    reviewCount: 1532,
    hook: 'Some of what you carry was never really yours. This reading names the family pattern behind it, checks how it shows up across your family, and one way to start setting it down.',
    whatYouGet: [
      'The specific pattern your family passed down, named clearly',
      'Where in your family line this pattern most likely started',
      'How this pattern has shown up differently across your family, while staying the same underneath',
      'The area of your life where this pattern is currently most active',
      'What has been protecting your family by keeping this pattern in place',
      'Whether this pattern shows up the same way for every family member, or hits some harder than others',
      'What breaking this pattern would actually change for the next generation',
      'Take one small action this week to start setting this pattern down',
    ],
    upsell: { id: 'family-destiny-synthesis', name: 'What Your Family Actually Passed Down', price: 69 },
  },
  {
    id: 'spiritual-gifts-reading',
    name: 'The Spiritual Gifts You Arrived With',
    tagline: 'The specific gifts you were born with, and how to actually use them',
    emoji: '✨',
    price: 29,
    domain: 'wellness',
    hook: 'You were born with real gifts most people never use. This reading names yours clearly, checks whether anyone has already noticed it, and shows one way to start using it.',
    whatYouGet: [
      'The specific gift you arrived with, named clearly',
      'Why you have likely underused this gift, and what got in the way',
      'Whether this gift is already strong in you, or still needs to be developed',
      'What using this gift looks like in normal daily life',
      'The moment where this gift is needed most but offered least',
      'Whether this gift has been recognized by others before, even if you dismissed it',
      'What this gift looks like once it is genuinely developed, not just first noticed',
      'Begin using it this week with one small, real step',
    ],
    upsell: { id: 'spiritual-scribe', name: 'The Spiritual Scribe', price: 24 },
  },
  {
    id: 'past-life-reading',
    name: 'What Your Soul Carried In',
    tagline: "What you carried into this life, and how it's shaping the one you're living now",
    emoji: '🕯️',
    price: 49,
    domain: 'wellness',
    isBestSeller: true,
    rating: 4.7,
    reviewCount: 1420,
    hook: 'Some patterns in your life do not match anything in your own history. This reading names what your soul carried in, checks how present it feels, and what to do with it.',
    whatYouGet: [
      'The specific pattern you most likely carried into this life',
      'The fear or pull that makes little sense given your actual history',
      'Where this carried pattern shows up most strongly in your life right now',
      'The skill or instinct that came unusually easily to you, more easily than your life explains',
      'What this pattern was likely trying to complete',
      'Whether this pattern has been getting stronger recently, or has always felt this present',
      'The kind of relationship most likely to trigger a strong, unexplainable recognition',
      'Take one small action this week that helps this pattern move toward completion, not repeat again',
    ],
    upsell: { id: 'spiritual-scribe', name: 'The Spiritual Scribe', price: 24 },
  },
  {
    id: 'chakra-blueprint-reading',
    name: "Where Your Energy Is Blocked, Where It's Open",
    tagline: 'Which of your energy centers are open, and which are quietly blocked',
    emoji: '🔓',
    price: 34,
    domain: 'wellness',
    rating: 4.7,
    reviewCount: 1698,
    hook: 'Energy does not move evenly through anyone. This reading shows exactly where yours is blocked and where it flows freely, whether that block is old or new, and one way to open it.',
    whatYouGet: [
      'Which parts of your energy are genuinely open right now, and which are blocked',
      'What is actually keeping the blocked parts closed',
      'How each block shows up in daily life, not just as a vague feeling',
      'Whether your biggest block is starting to loosen, or still fully closed',
      'The practice that fits your specific pattern, not a generic routine',
      'Whether this block has been present your whole life, or started after a specific event',
      'The area of your life most likely to improve first once this block clears',
      'Try one simple practice this week to start opening your biggest block',
    ],
    upsell: { id: 'health-scribe', name: 'The Health Scribe', price: 24 },
  },
  {
    id: 'dark-night-navigator',
    name: 'Getting Through Your Hardest Spiritual Season',
    tagline: 'A guided reading built specifically for a genuine dark night of the soul',
    emoji: '🌒',
    price: 49,
    domain: 'wellness',
    rating: 4.9,
    reviewCount: 892,
    hook: 'This is not for an ordinary hard week. This reading shows exactly where you are in this season, whether it has a clear starting point, and whether the hardest part is ending.',
    whatYouGet: [
      'Exactly where you are right now inside this hard season',
      'What is genuinely ending, not just what feels unstable',
      'What is quietly forming underneath the hardship, even if you cannot see it yet',
      'Whether the hardest part of this season is still building, or already starting to ease',
      'Why your usual coping methods have stopped working, and what that actually means',
      'Whether this season has a clear starting point you can name, or has built up slowly',
      'What is most likely to make this season harder than it needs to be',
      'Use one grounding practice this week that fits this exact stage',
    ],
    guidanceType: 'practical-solution',
    guidanceText: 'A grounding practice built specifically for this stage of the process, not a generic self-care suggestion.',
    upsell: { id: 'spiritual-scribe', name: 'The Spiritual Scribe', price: 24 },
  },
  {
    id: 'intuition-activation-reading',
    name: 'Learning to Trust Your Intuition',
    tagline: "Where your intuition has already been right, and why you've doubted it anyway",
    emoji: '👁️',
    price: 29,
    domain: 'wellness',
    hook: 'Most people who say they do not trust themselves actually have a strong track record of being right. This reading proves it, checks where this doubt hits hardest, and shows you how.',
    whatYouGet: [
      'Real proof, from your own life, of where your intuition has already been right',
      'Why you have overridden it anyway, named clearly',
      'The real difference, for you personally, between intuition and simple anxiety',
      'The situation where your intuition is strongest and most reliable',
      'Whether your intuition is naturally strong, or something you still need to practice trusting',
      'Whether this doubt shows up more in relationships, work, or your own body',
      'The specific person or voice most likely to talk you out of trusting it',
      'Try one practice this week to hear your intuition more clearly',
    ],
    upsell: { id: 'spiritual-scribe', name: 'The Spiritual Scribe', price: 24 },
  },
  {
    id: 'vitality-code',
    name: 'The Vitality Code',
    tagline: "Your natural energy pattern, and what's actually been draining it",
    emoji: '⚡',
    price: 29,
    domain: 'wellness',
    isPopular: true,
    rating: 4.8,
    reviewCount: 2210,
    hook: 'Feeling tired for no clear reason usually has a real cause. This reading finds yours, checks whether this pattern is new or long-standing, and shows one thing that will genuinely help.',
    whatYouGet: [
      'Your natural energy pattern, named clearly',
      'What is actually draining your energy, which may have nothing to do with sleep',
      'What genuinely restores your energy, not what is just popular advice',
      'The time of day your energy is naturally strongest',
      'Whether your low energy points to a bigger pattern worth watching',
      'Whether this pattern has been consistent for years, or has changed recently',
      'The specific habit most likely making this worse without you realizing it',
      'Make one simple change this week that will genuinely help your energy',
    ],
    upsell: { id: 'health-scribe', name: 'The Health Scribe', price: 24 },
  },
  {
    id: 'abundance-frequency-audit',
    name: 'Do You Actually Feel Like You Have Enough',
    tagline: 'Your actual relationship with enough, and where scarcity thinking took root',
    emoji: '🌾',
    price: 34,
    domain: 'wellness',
    hook: 'Feeling like you never have enough is not always about money. This reading shows where this feeling really started, whether it changes around certain people, and how to change it.',
    whatYouGet: [
      'Where your feeling of not having enough most likely began',
      'How this feeling shows up in decisions that have nothing to do with money',
      'The area of your life where this feeling is strongest right now',
      'The real difference between having more and actually feeling like it is enough',
      'Whether this feeling is deeply set in you, or can shift with practice',
      'Whether this feeling gets stronger around certain people, or stays the same regardless',
      'What having genuinely enough would actually let you stop doing',
      'Practice one small decision this week from a place of enough, not fear',
    ],
    upsell: { id: 'spiritual-scribe', name: 'The Spiritual Scribe', price: 24 },
  },
  {
    id: 'sleep-and-dreams-reading',
    name: 'What Your Dreams Are Telling You',
    tagline: 'What your recurring dreams are actually pointing to',
    emoji: '🌙',
    price: 29,
    domain: 'wellness',
    hook: 'Repeating dreams are rarely random. This reading names the real theme behind yours, checks how long it has been recurring, and one way to work with it while awake.',
    whatYouGet: [
      'The real theme most likely behind your repeating dreams',
      'Why this theme is showing up in dreams instead of in your waking thoughts',
      'The part of your waking life this theme is most connected to',
      'Whether this theme is close to being resolved, or still just beginning to surface',
      'One way to work with this theme consciously, not only while you sleep',
      'Whether this dream has become more frequent recently, or has always shown up occasionally',
      'The specific decision or relationship this dream is most likely trying to prepare you for',
      'Try one small practice tonight before bed to invite more clarity',
    ],
    upsell: { id: 'health-scribe', name: 'The Health Scribe', price: 24 },
  },
  {
    id: 'purpose-activation-reading',
    name: 'Living Your Purpose, Not Just Knowing It',
    tagline: 'The gap between knowing your purpose and actually living it day to day',
    emoji: '🔥',
    price: 34,
    domain: 'wellness',
    rating: 4.7,
    reviewCount: 1345,
    hook: 'Knowing your purpose and actually living it are two different things. This reading shows the real gap, checks how long it has been open, and one way to close it.',
    whatYouGet: [
      'The specific gap between what you know about your purpose and how you are actually living',
      'What is really in the way, day to day, not the excuse you have been blaming',
      'The smallest way this purpose could show up in an ordinary week',
      'The fear most likely keeping this gap in place',
      'Whether you are entering a life stage that makes closing this gap more likely now',
      'Whether this gap has been present for years, or opened up more recently',
      'The specific fear underneath the fear you already knew about',
      'Make one small decision this month that starts closing the gap',
    ],
    upsell: { id: 'spiritual-scribe', name: 'The Spiritual Scribe', price: 24 },
  },
  {
    id: 'spirit-attachment-reading',
    name: 'The Energetic Ties You Didn\'t Choose',
    tagline: "The energetic connections you're still carrying, and what they're actually here for",
    emoji: '🔗',
    price: 34,
    domain: 'wellness',
    hook: 'Some strong pulls toward people or places were never fully your choice. This reading names the real ties you are still carrying, checks how they have changed, and one way to work with them.',
    whatYouGet: [
      'The specific ties you are still carrying, named clearly',
      'Where each one most likely started, in family, an old event, or something further back',
      'Whether each tie is actually helping you or quietly draining you',
      'The part of your life where these ties show up most, without you realizing it',
      'Whether a tie is close to resolved, or still fully active',
      'Whether this tie has gotten stronger or weaker as your life has changed',
      'The specific circumstance most likely to bring an old tie back into focus',
      'Start working with your strongest tie this week using one simple action',
    ],
    upsell: { id: 'spiritual-scribe', name: 'The Spiritual Scribe', price: 24 },
  },
  {
    id: 'unresolved-vow-reading',
    name: 'The Promise You Made in Another Life',
    tagline: "The vow you're still unconsciously keeping, and what renegotiating it actually looks like",
    emoji: '🕊️',
    price: 34,
    domain: 'wellness',
    hook: 'Some patterns make no sense given your real history. This reading names the old promise behind it, checks where it shows up most, and one way to finally let it go.',
    whatYouGet: [
      'The specific promise you appear to still be unconsciously keeping',
      'What kind of situation this promise most likely came from',
      'Where it shows up now, in choices that have nothing to do with where it started',
      'What this promise was protecting you from, and whether you still need that protection',
      'Whether this promise is close to being released, or still firmly in place',
      'Whether this promise shows up more in relationships, work, or how you treat yourself',
      'What consciously choosing differently, just once, would actually prove to you',
      'Take one small action this week to start letting this promise go',
    ],
    upsell: { id: 'spiritual-scribe', name: 'The Spiritual Scribe', price: 24 },
  },
]

export const getWellnessToolById = (id: string) => wellnessTools.find(t => t.id === id)
export const getPopularWellnessTools = () => wellnessTools.filter(t => t.isPopular)
